### ISSUE TITLE
notifications stay in android even after messages are read - requires manual clear of EVERY push notification

### ISSUE THREAD

**Issue by thankstipscom** [RocketChat/Rocket.Chat.ReactNative#4506] opened 2022-09-07 21:26 UTC
### Description:

Unread message on android quick settings notification screen and in the notifications section in the top left is always there even if the message its referencing is read on the device or on another device.

### Environment Information:

- Rocket.Chat Server Version: 5.1
- Rocket.Chat App Version: 4.30.0.35021 (also same behavior on latest non experimental app)
- Device Name: Note 10+ (happens on multiple devices so probably all androids)
- OS Version: 12

### Steps to reproduce:

1. Receive a new message
2. Wait for push notification to come on phone
3. Check message on PC app or web
4. Without clearing the push notification on the phone, open rocket chat and check the message so its read
5. Notice the push notification doesn't disappear

### Expected behavior:

Notification of new message should go away when the message is read on phone or any other device of the same account.

### Actual behavior:

"New Unread Message" notification persists forever regardless of whether the message is read on the phone or any other place of the same user. All push notifications need to be manually cleared which is annoying.

### Additional context:

Tested same behavior with SMS application (Chomp). Notification at the top DOES clear if the SMS is read in the SMS app. Doesnt require any manual clearing.

![image](https://user-images.githubusercontent.com/12487888/188983730-2c614b2d-88a7-42b3-822e-51c430a8629d.png)
![image](https://user-images.githubusercontent.com/12487888/188984169-924c0da3-6687-4a5a-b79d-a0816e7fd347.png)

**Comment by ankar84** [comment] 2022-09-08 06:15
Duplicate of https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1099

**Closed** 2022-09-08 13:44 UTC
