### ISSUE TITLE
single-server branch specific issue - Android - Notification doesn't load app into workspace when app is closed.

### ISSUE THREAD

**Issue by BizClimb** [RocketChat/Rocket.Chat.ReactNative#2329] opened 2020-07-21 21:35 UTC
- Your Rocket.Chat Experimental app version: 4.9.0.1
- Your Rocket.Chat server version: 3.4.2
- Device (or Simulator) you're running with: Android

I am using Firebase notifications set via google-services.json file on single server branch. This started happening after 4.5. (4.8 and now 4.9 still happening) When I get a notification and the rocketchat app is closed, it opens, but then stays on the loading splash screen without moving any further. I have to then force close and re-open the app. If the app is already open in the background though, the notification works fine, it's only when the app is closed, and the notification itself opens the app when clicking it.

You can test by sending yourself the push notification via admin panel, once it comes in, click it (make sure app is closed) and it will load splash screen, then becomes non responsive.

**Comment by diegolmello** [comment] 2020-07-22 12:19
I have a single-server app installed and it's working nicely.
Make sure you've followed our whitelabel docs https://docs.google.com/document/d/17ib2Le_SH6U2gP0sEuKapF2J-WgqZxPFMRRVUSofz7Y/edit

**Comment by BizClimb** [comment] 2020-07-23 03:25
I followed the white label guide, still didn't work. Only difference between the white label guide and what I did was I compiled signed APK with Android Studio instead of command line. I even created a firebase project with chat.rocket.reactnative so I basically didn't have to change anything just to be sure that nothing got "lost" during whitelabeling, I only changed the server url in app.json root and that's it. For some reason it's still freezing at splash screen. 

I will continue playing around with it, and try to eventually get a release APK generated with command line instead of android studio to see if that solves the issue.

**Comment by diegolmello** [comment] 2020-07-23 12:15
@BizClimb Ok. Please, open a PR when you find the issue. Thanks.

**Comment by BizClimb** [comment] 2020-07-27 23:21
Tried compiling from command line, tried different OSs to compile, and also just running without compiling with npx react-native run-android. Issue persists regardless, unable to find the cause, but I assume whatever code processes inbound firebase notifications isn't properly opening the correct channel/server in app.json AFTER opening the app correctly.

You can re-create with the following these steps exactly:
1. Clone single branch react native
   - git clone https://github.com/RocketChat/Rocket.Chat.ReactNative.git --branch single-server --single-branch
2. Create Google firebase project with bundle chat.rocket.reactnative and download google-services.json file.
3. Download google-services.json from Google Firebase and place file to your /android/app/ folder.
4. Edit /app.json server entry to: "server": "http://chat.bizclimb.com:3000", (but replace with your test server not mine haha).
5. Go to Admin -> Push ->
	- Disable Gateway (Uncheck Enable Gateway)
	- In Certificates and Keys section set your GCM API Key and GCM Project Number as shown in whitelabel guide.
6. Save (and restart rocketchat)
	- sudo systemctl restart rocketchat
7. Run npx react-native run-android (or compile APK and install if you prefer).
8. Open the Rocket.Chat Experimental and once it loads login to your account to make sure you're registered for push notifications on this device.
9. Force close the rocket chat app after login (close it completely, don't let it run in the background).
10. Login from another device / web browser, go to Admin -> Push and click Send a test push to my user.
11. You'll get a push notification on your android device / emulator / etc...
12. Open the push notification, it loads the Rocket.Chat Experimental app but then hangs (does not load your server, channel, room, etc..).

NOTE: * If you don't completely force close the app, it does work fine to load the notification, so it has something to do with the step of logging in, perhaps to a single server workspace?

Hope this helps someone identify the issue.

**Comment by diegolmello** [comment] 2020-07-28 11:58
Did you try with a normal push from a user?
`Send a test push` is only to confirm push configuration is working and the app doesn't implement it, because this push data doesn't have host or content.

**Comment by BizClimb** [comment] 2020-07-28 15:41
Yes, same result with a real user message as well, and another note (probably related but not sure), the in notification reply does not get delivered either.

**Comment by diegolmello** [comment] 2020-07-28 15:47
http://chat.bizclimb.com:3000/ your server must be secure.

**Comment by BizClimb** [comment] 2020-07-28 15:50
This was just an extra test server I spun up for testing, my production server is secured with SSL (HTTPS) and is having the same behavior.

**Comment by BizClimb** [comment] 2020-07-28 17:40
Just to be sure I secured the server Via SSL using nginx via the guide here: https://docs.rocket.chat/installation/manual-installation/configuring-ssl-reverse-proxy/

changed the server in app.json from http://chat.bizclimb.com:3000 to https://chat.bizclimb.com

Re-compiled and ran, same two issues persist:
1. If the app is completely closed, it will open from the notification but freeze at splash screen.
2.,Regardless if app is open or not, in notification reply message does ever get to room.

Nothing in the react-native debug console so not really sure what else I can do to help identify the issue.

**Comment by diegolmello** [comment] 2020-07-28 18:44
First, make sure you have [Reactotron](https://github.com/infinitered/reactotron) installed.

You'll have to run [this](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/ReactotronConfig.js#L17) so the app is connected to Reactotron.
Then run the debug app on your device and make sure the logs are flowing like [this](https://user-images.githubusercontent.com/804994/88707573-d0a9cb00-d0e8-11ea-8b98-7ee6cbaa8801.png).

Put a `console.log(notification)` [here](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/notifications/push/push.android.js#L13).

After that, you can either have some idea of what's going on or use this approach to help us figuring your issue.

**Comment by BizClimb** [comment] 2020-07-28 21:36
I setup reactotron, here is the log for it when it loads the app from the notification and freezes.
[reactotron_timeline.txt](https://github.com/RocketChat/Rocket.Chat.ReactNative/files/4991271/reactotron_timeline.txt)

Doesn't look like there was any output for console.log for the notification even though I did add the code as such:
NotificationsAndroid.setNotificationOpenedListener((notification) => {
			console.log(notification);
			this.onNotification(notification);
		});

**Comment by diegolmello** [comment] 2020-07-29 12:59
I see this:
```
{"type":"DEEP_LINKING_OPEN","params":{"path":"undefined/undefined"}}},"type":"state.action.complete"},
```

So something called it and it's probably being called by that notification.
Can you try again?
I can't help you with enough information.

**Comment by BizClimb** [comment] 2020-07-29 18:11
Sure, absolutely, how do I get more information in regards to that? Is there a way I can make reactotron more verbose then it is already or is there something else I should do?

**Comment by diegolmello** [comment] 2020-07-29 18:21
Reactotron shows all logs the same way RN debugger (but faster).
Log this whole notification tap and see what's going on.

**Comment by BizClimb** [comment] 2020-07-29 20:21
![image](https://user-images.githubusercontent.com/60819768/88847038-17142e00-d1ac-11ea-8b55-3512d8f502fc.png)

The log I exported above is from the notification tap until freeze, I'm not seeing any "additional" data in Reactotron though.

**Comment by BizClimb** [comment] 2020-07-29 20:37
![image](https://user-images.githubusercontent.com/60819768/88850652-4e390e00-d1b1-11ea-8d31-e1b53fd9d772.png)
This is the entire reactatron log from tap to freeze expanded completely.

**Comment by BizClimb** [comment] 2020-07-30 19:28
Is it possible we're looking in the wrong spot, and the receiving end is fine, it's when the outgoing notification is created it might be missing the "action" or an identifier where the notification is supposed to bring the user? Sounds like what might be happening if Deep Linking everything is undefined?

**Comment by djorkaeffalexandre** [comment] 2020-07-31 19:29
Hey @BizClimb, I guess your problem is related to [this](https://github.com/RocketChat/Rocket.Chat/pull/18442), it'll be merged ASAP to a new server release. (3.5.1)
Update your server ASAP and let's test if this is the problem. :)
Let us know if it works.
Thanks in advance.

**Comment by BizClimb** [comment] 2020-07-31 19:49
3.4.3 is showing as latest release, even though 3.5.0 (which is what I upgraded to) is the release before. I don't see a 3.5.1 yet.

**Comment by djorkaeffalexandre** [comment] 2020-07-31 19:52
@BizClimb
> it'll be merged ASAP to a new server release.
It's not merged yet :)
I've said to you stay tuned and update when the new version launch, then we can see if it fixes your problem.

**Comment by BizClimb** [comment] 2020-07-31 19:53
Excellent, I'll be waiting, will update as soon as it's merged and live.

**Comment by BizClimb** [comment] 2020-08-04 02:12
Issue still persists, even after I upgraded to 3.5.1. :(

**Comment by diegolmello** [comment] 2020-08-04 12:28
@BizClimb We're releasing version 4.10 right now.
It's on beta phase.
Next week, we're going to update the single-server branch to match the new version and I'll check this.
If you manage to find the root cause first, please open a PR.
Thanks.

**Comment by BizClimb** [comment] 2020-08-04 18:34
Sounds good, I wasn't able to edit this issue title after I created it, but this bug does appear in the **normal branch** too, not only the single server, so I'll be able to test as soon as 4.10 comes out with the normal branch also.

**Comment by diegolmello** [comment] 2020-08-04 19:01
Oh, I didn't know that.
So it should be really easier to reproduce, but still...
We use https://open.rocket.chat all day with no issues.

**Comment by BizClimb** [comment] 2020-08-05 03:40
I'm guessing most people use the RC gateway instead of direct firebase, maybe the gateway passes some kind of information that direct firebase notification does not?

Yes, it's really simple to re-create the bug, just compile with your own google-services.json (don't use gateway), and set the GCM  Server ID & API in the credentials. Launch and login to your server on the app to register the device to get push, then close app, in web browser send test push or via another user send a message, push notification in app comes in, click it, rocket starts to load, then hangs at splash.

**Comment by BizClimb** [comment] 2020-08-05 03:49
I will test again and report back once 4.10 is out.

**Comment by diegolmello** [comment] 2020-08-05 11:41
> Yes, it's really simple to re-create the bug, just compile with your own google-services.json (don't use gateway), and set the GCM Server ID & API in the credentials. Launch and login to your server on the app to register the device to get push, then close app, in web browser send test push or via another user send a message, push notification in app comes in, click it, rocket starts to load, then hangs at splash.

We do this kind of test every other day and it's working.

**Comment by BizClimb** [comment] 2020-08-05 15:14
Hmm, I've compiled the code via android studio, command line, and straight npx react-native run-android and still get the same result. I tried a RC server behind reverse proxy via nginx and apache, same result as well. I'm only using Android, not iOS so maybe a step for iOS is required even though I'm not using it?

I'll do a full video run through of what I'm doing from server setup, to compile, to freezing at flash screen, and maybe we can see if some step is missing.

**Comment by SpirouSp** [comment] 2020-08-07 17:29
Hello. I have had the same issues as you described but on iOS. After reading some topics on github and getting some help on chat, I found my problem: the url in the Admin Panel / General should be the same as the url used in the mobile application. After I changed this the individual  notifications are working again.

 I haven’t checked notifications two more then one user, so I don’t know if the issue related in 18442. But if a user has more then one app token, it isn’t working without this fix. I hope this fix will solve that problem too.

**Comment by BizClimb** [comment] 2020-08-07 20:26
Thanks for the suggestion, I tried both the correct url and even the direct http://server:3000 url and neither resolved the issue.

**Comment by BizClimb** [comment] 2020-08-07 20:56
I thought maybe I could get some more details from react-native log-android, I got this output from notification tap to freeze:

info Starting logkitty
[15:41:55] D | ReactNative ▶︎ ReactInstanceManager.ctor()

[15:42:08] D | ReactNative ▶︎ ReactInstanceManager.createReactContextInBackground()
                           └ ReactInstanceManager.recreateReactContextInBackgroundInner()

[15:42:10] D | ReactNative ▶︎ ReactInstanceManager.onJSBundleLoadedFromServer()

[15:42:10] D | ReactNative ▶︎ ReactInstanceManager.recreateReactContextInBackground()
                           └ ReactInstanceManager.runCreateReactContextOnNewThread()

[15:42:10] D | ReactNative ▶︎ ReactInstanceManager.createReactContext()

[15:42:10] D | ReactNative ▶︎ Initializing React Xplat Bridge.

[15:42:10] D | ReactNative ▶︎ Initializing React Xplat Bridge before initializeBridge

[15:42:12] D | ReactNative ▶︎ Initializing React Xplat Bridge after initializeBridge
                           └ CatalystInstanceImpl.runJSBundle()

[15:42:12] D | ReactNative ▶︎ ReactInstanceManager.setupReactContext()
                           └ CatalystInstanceImpl.initialize()

[15:42:12] D | ReactNative ▶︎ ReactInstanceManager.attachRootViewToInstance()

[15:42:12] D | ReactNative ▶︎ ReactInstanceManager.createReactContextInBackground()
                           └ ReactInstanceManager.attachRootViewToInstance()

[15:42:15] I | ReactNative ▶︎ [GESTURE HANDLER] Initialize gesture handler for root view com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView{e41b49f V.E...... ......ID 0,0-1080,2022 #1}

I'll wait until 4.10 is out and then will re-do my tests.

**Comment by BizClimb** [comment] 2020-09-07 20:00
Just tried this on the regular repo (not single server) and it is better (not 100%) it opens the correct server, but does not go to the right conversation, just opens the rooms list. On the single server branch it still freezes on load.

**Comment by diegolmello** [comment] 2020-09-09 12:41
I tried both develop and single-server and it worked fine.
It's something on your env.

**Closed by diegolmello** 2020-09-09 12:41 UTC
Labels: ℹ️ needs info
