### ISSUE TITLE
[BUG] Push notification opens a list with chats

### ISSUE THREAD

**Issue by C1ean** [RocketChat/Rocket.Chat.ReactNative#2870] opened 2021-02-04 16:02 UTC
### Description:
Push notification when the application is minimized opens the list of chats if a channel not associated with the current notification was opened before.

### Environment Information:

- Rocket.Chat Server Version: 3.5.1
- Rocket.Chat App Version: 4.14.0
- Device Name: Iphone 11 Pro
- OS Version: 14.2

### Steps to reproduce:

For example, there are two channels - A and B.
I open channel A, minimize the application.
If  receive a notification to channel B, I click on it - instead of opening channel B, a list with chats opens.
If a notification arrives on channel A, then the channel will open successfully, as expected.

### Expected behavior:

When a notification arrives, a channel opens where it is contained

### Actual behavior:

The chat list opens if the last opened channel does not match the notification channel

### Additional context:

Critical bug

**Comment by C1ean** [comment] 2021-02-05 14:36
@diegolmello Do you have reproduce this problem? is there a chance to get the fix in the foreseeable future?

**Comment by diegolmello** [comment] 2021-02-05 14:41
@C1ean That's what I've been working on and we want to release a fix asap.
The fix is a little broader though.
The idea is to fix some issues found when the app is a while on background and it's killed by the OS. If that happens and the app is opened from the push notification, it might have a weak connection.
It's hard to reproduce it though, since any change requires the app to be on background for a while.

**Comment by diegolmello** [comment] 2021-03-23 13:39
Fixed on #2894

**Closed by diegolmello** 2021-03-23 13:39 UTC
Labels: 🐛 bug
