### ISSUE TITLE
Error when non-support setting change is received via stream

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#4805] opened 2023-01-12 14:02 UTC
#### Overview

We don’t support all Rocket.Chat settings on mobile, so we don’t fetch them all.

We don’t even fetch the supported ones on the same request https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/9525ef25d8e425f91861eea90a1cbecc716f8ec7/app/lib/methods/getSettings.ts#L146

But that’s not the issue.

The issue is that when we receive a setting has changed event of a non-supported setting from socket, an error is raised. The error is actually handled, but we can avoid it.

`ERROR  [Diagnostic error: Record settings#theme-font-body-font-family not found]`

I’m pretty sure it’s from here https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/9525ef25d8e425f91861eea90a1cbecc716f8ec7/app/lib/services/connect.ts#L135

#### To be done

- Fix the issue

**Comment by 456535688765** [comment] 2023-02-26 14:55
please assign me this issue

**Comment by GopalVerma1303** [comment] 2023-12-31 15:16
Hey @diegolmello! I am interested in solving this issue. Can you please assign it to me.

**Comment by diegolmello** [comment] 2024-01-11 14:52
You don't have to be assigned to work on open source. Be proactive and work on it. Thanks.

**Comment by GopalVerma1303** [comment] 2024-01-14 10:32
Hey @diegolmello! Your explanation on this issue was really helpful. But, can you please provide us with more references(files names or code snippets) that you think might be helpful to backtrack the root cause.  Thank you.

**Comment by diegolmello** [comment] 2024-01-15 12:31
- open the app in debug/dev mode
- on browser, change any Rocket.Chat setting that's not supported by the app https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/9109b8726912301b5b5e0fa159e814ad7a6c81e3/app/lib/constants/defaultSettings.ts#L29
- You should be able to see `ERROR  [Diagnostic error: Record settings#theme-font-body-font-family not found]` on Reactotron or Metro

The fix should be just a new if.

**Comment by GopalVerma1303** [comment] 2024-01-15 21:09
Thankyou @diegolmello!

Essentially, creating new array of `nonSupportingSettingsKeys` just like this:
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/9525ef25d8e425f91861eea90a1cbecc716f8ec7/app/lib/methods/getSettings.ts#L15-L43
And hence adding a new "if" condition, so that the app doesn't make call to that setting `_id` which is present in `nonSupportingSettingsKeys` will resolve this bug. Is my approach correct?

**Comment by diegolmello** [comment] 2024-01-15 21:12
@GopalVerma1303 how are you going to know which settings aren't supported?

**Closed** 2024-01-22 22:40 UTC
Labels: 🐛 bug, 🍭 good first issue
