### ISSUE TITLE
Remove i18n keys not in use

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#4860] opened 2023-01-24 19:00 UTC
We have a couple of i18n keys set without being used on the app.
Identify and remove them from all languages.
Use `i18n/locales/en.json` as base.

**Comment by ronaksingh27** [comment] 2023-01-26 14:26
Heyy... could you assign this issue to me ??

**Comment by Neel-shetty** [comment] 2023-04-02 19:32
Is this issue fixed? I checked the code and the unused keys seem to be removed.
Confused because the issue is still open.

**Closed** 2023-06-26 19:28 UTC
Labels: 🍭 good first issue, 🚚 chore
