### ISSUE TITLE
Android App Showing Blank Page When Phone Default Language is Set to Hebrew

### ISSUE THREAD

**Issue by isaacvonaaron** [RocketChat/Rocket.Chat.ReactNative#2594] opened 2020-11-01 09:52 UTC
### Description:

App showing blank page when phone default language is set to Hebrew.

### Environment Information:

- Rocket.Chat Server Version: 3.7.1
- Rocket.Chat App Version: 4.11, also tested 4.10 and 4.8
- Device Name: Samsung Galaxy S10+
- OS Version: Android 

### Steps to reproduce:

1. Use an android device
2. Go to settings, language, configure Hebrew as the default language
3. Stop the Rocket.Chat app if running
4. Run the app

### Expected behavior:

English UI since there is no support for Hebrew.

### Actual behavior:

Blank screen
https://imgur.com/0WPLsEV

### Additional context:

As stated, I didn't expect a Hebrew interface, just my second preference which is English.

![WhatsApp Image 2020-11-01 at 10 48 19](https://user-images.githubusercontent.com/10384285/97798598-2a61ea00-1c30-11eb-9399-b41c8d713039.jpeg)

**Comment by diegolmello** [comment] 2020-11-05 19:46
I wasn't able to test it.
I'm not sure which one is Hebrew here.
Can you give us more info?
Thanks!

**Comment by isaacvonaaron** [comment] 2020-11-06 06:27
Hi Diego

The screen is blank. It is blank in any language - Hebrew, English, Chinese... 

To get to this blank screen you have to switch the Android device's primary language to Hebrew and the start the Rocket.Chat app, which has to be terminated prior to opening it.

I must emphasize that otherwise the Rocket.Chat app functions OK when the phone is switch to English as primary language. I can even configure the app and English, switch to Hebrew and then:
1. If I don't terminate the app, the already running app will still work, in English.
2. Even after restarting the phone in Hebrew while the app shows this blank screen, the service worker keeps running and I still get audio notifications. This is useful if a second app like Parrot Chat is installed.

**Comment by diegolmello** [comment] 2020-11-06 11:45
I tried changing the default language and I couldn't reproduce the issue, but I'm not sure which one is Hebrew on the OS selection.
Can you screenshot?
I have a S10e, so it's probably similar to yours.

**Comment by isaacvonaaron** [comment] 2020-11-06 13:34
Sure, does that help?
עברית (ישראל)
Means Hebrew (Israel)

I also tried to shoot its placement on the language selection list but my phone offers Hebrew as a suggestion, which places it at the top.

![WhatsApp Image 2020-11-06 at 15 30 05](https://user-images.githubusercontent.com/10384285/98371609-1c9fd080-2045-11eb-9bdb-ffb8661ea8a9.jpeg)

**Comment by djorkaeffalexandre** [comment] 2020-12-02 16:38
This was a problem related to RTL languages fixed by #2656.

**Closed by djorkaeffalexandre** 2020-12-02 16:38 UTC
Labels: ℹ️ needs info
