### ISSUE TITLE
users' avatars not appearing in mobile app connected to a rocketchat installation that uses avatar external provider URL

### ISSUE THREAD

**Issue by wokawoka** [RocketChat/Rocket.Chat.ReactNative#3362] opened 2021-09-01 16:05 UTC
### Description:
I run a rocket.chat installation that works correctly. Avatars are regularly sourced from an open URL (which doesn't need authentication) through the "Avatar External Provider URL" field in rocket.chat settings.
Avatars are regularly fetched and shown when our users are connecting to the rocket.chat interface via web. 

I then connected the android rocket.chat app to the same rocket.chat installation and unfortunately it looks like that the Avatar External Provider URL option is completely ignored so that the default user avatars (composed by the initials) plus just the default users like Rocket.Cat one shown instead of the avatars from the URL.

Any idea or hint on how to fix that?
Thank you!

### Environment Information:

- Rocket.Chat Server Version: 3.17.0
-  NodeJS Version: 12.18.4 - x64            
-  MongoDB Version: 4.0.26  
- Rocket.Chat App Version: 4.18.0.24757 / Rocket.Chat experimental app 4.19.0
- OS Version: Android 10

### Steps to reproduce:

1. set Avatar External Provider URL in rocket.chat options with a valid URL from which to source the avatars
2. connect via rocket.chat android app
3. avatars are not fetched from the above URL, the default installation avatars are shown instead

**Comment by tensor5g** [comment] 2022-01-18 23:45
Getting the same issue, can't believe it hasn't been fixed yet

**Comment by larcefox** [comment] 2022-03-08 01:01
Getting the same issue.
I think that happens because app can't accept self signed certificate.

**Comment by tensor5g** [comment] 2022-03-08 01:07
I don't think that is true. My app is behind a reverse proxy with a letsencrypt certificate (both the rocket.chat app and the server hosting the user's avatars).

**Comment by wokawoka** [comment] 2022-03-18 11:29
I just think that the app is ignoring the custom avatar settings. It is still able to correctly displaying the default rocket chats avatars (rocket cat and other rocket chat app bot avatars) which never show up when you are using a custom avatar path.
I just think that the developers should acknowledge this issue, in the meanwhile I'll soon try to correct the problem by playing with my nginx config.

**Comment by diegolmello** [comment] 2022-03-18 13:10
What kind of external provider do you use? Let's plan a fix for this.

**Comment by tensor5g** [comment] 2022-03-18 13:34
I use a self hosted/self programmed image provider. nginx reverse proxy -> apache webserver -> PHP site. Works just fine on desktop.

**Comment by diegolmello** [comment] 2022-03-18 13:40
Are you aware of any free services we could use for development and QA?

**Comment by tensor5g** [comment] 2022-03-18 13:52
I believe we can just use a static image as the url provider and we can reproduce the issue with that. 
https://www.iana.org/_img/2022/iana-logo-header.svg for example

**Comment by diegolmello** [comment] 2022-03-18 13:55
Oh, do you use SVGs for that? That might be the reason.
Mobile apps don't work with SVGs easily.
We'd need to _know_ the image is SVG and then use a lib to draw it in runtime.
Can you try using a PNG on your provider to test if is working?

**Comment by tensor5g** [comment] 2022-03-18 14:08
Sorry, that was just a static image I found quick for testing. I do use PNGs for my external avatars.

**Comment by wokawoka** [comment] 2022-03-18 15:15
> What kind of external provider do you use? Let's plan a fix for this.
Here we just use an "Avatar External Provider URL" pointed to our nextcloud installation (https://our.nextcloud.domain/avatar/{username}/120 . 

It works perfectly on desktop (only system users like Rocket.Cat or bots from apps like the GIPHY bot user are not displaying their avatar when switching to the external provider URL, but I guess I could fix that by tweaking the nginx reverse proxy that is in front of rocket chat.

With this exact same setup our custom avatars are not shown on the ANDROID APP, while the avatars of Rocket.Cat and of the GIPHY bot are correctly shown, like if the app is completely disregarding the "Avatar External Provider URL" setting.

Thank you for you help!

**Comment by diegolmello** [comment] 2022-03-18 16:31
Thanks. I'll try to plan a fix for next sprint.

**Comment by wokawoka** [comment] 2022-03-21 10:38
> Thanks. I'll try to plan a fix for next sprint.

it's great to hear that, thank you very much for your work

**Closed** 2022-04-19 00:52 UTC
Labels: 🐛 bug

**Comment by tensor5g** [comment] 2022-04-29 13:13
Just got this update on Android and it's not quite working. This is the request it's generating:
```/api/avatar?rcusername=test?format=png&size=36undefined```
This is what it's configured to use
```/api/avatar?rcusername={username}```
It's adding extra parameters which the desktop isn't. This probably wouldn't be a problem if it didn't put a second "?" parameter after the first one which makes the request invalid. I can work around this by rearchitecting how my api takes requests, but it seems like a bug.
