### ISSUE TITLE
Preview mode for private chat when open from notification

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#2170] opened 2020-06-08 14:04 UTC
- Your Rocket.Chat Experimental app version: 4.7.0.17188
- Your Rocket.Chat server version: 3.1.1
- Deviceyou're running with: Xiaomi Mi 9 SE

**Update: Replicate conditions are still investigating.**
User1 was added to private chat. Then User2 write a message to that private chat so User1 gets that message as push notification. User1 taps on that push notification and gets to strange preview mode. In fact, user is a member of that private chat, so any preview mode is a bug.
When User1 tap back to go to RoomListView and then tap to that private chat again + no preview mode and join button.
![image](https://user-images.githubusercontent.com/4023037/84096326-59ba5500-aa0a-11ea-9088-ec5d65d06c97.png)

**Comment by diegolmello** [comment] 2020-07-20 12:13
I was unable to reproduce it.
Is it still happening?

**Comment by ankar84** [comment] 2020-07-20 12:30
> I was unable to reproduce it.

It happened once to one of my users. And I did reproduce that once, but then I couldn't reproduce that any more.
So, I think that circumstances of that issue are need to be clarified.

**Comment by diegolmello** [comment] 2020-07-20 12:33
Ok.
I'm going to close it then.
Please reply with a reproducible example if you manage to get one.
Thanks.

**Closed by diegolmello** 2020-07-20 12:33 UTC
Labels: ℹ️ needs info
