### ISSUE TITLE
Push notifications don't disappear after chats being read in Android 4.32.0

### ISSUE THREAD

**Issue by seregasoft** [RocketChat/Rocket.Chat.ReactNative#4617] opened 2022-10-18 08:17 UTC
### Description:

Push notifications don't disappear after chats being read

### Environment Information:

- Rocket.Chat Server Version: 4.8.1
- Rocket.Chat App Version: Android white-label 4.32.0, 4.31.0 
- Device Name: Pixel 3, Nexus 5X
- OS Version: 12, 8.1

### Steps to reproduce:

- App closed
- Receive a push notification(s)
- Open the app by icon (not push notification bar)
- Read all unread chats

### Expected behavior:

All push notifications are gone

### Actual behavior:

All push notifications are still there

### Additional context:

This problem is not present in version 4.26

**Comment by GleidsonDaniel** [comment] 2022-10-18 11:28
It really isn't working properly.

**Comment by ankar84** [comment] 2022-10-19 15:17
looks like duplicate of https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1099

**Comment by diegolmello** [comment] 2022-10-19 16:12
@ankar84 Not really. They should disappear on app resume. It's not about reading on other clients and dismissing automatically.

**Closed** 2022-12-21 16:07 UTC
Labels: 🐛 bug
