### ISSUE TITLE
Cannot properly rename channel

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat.ReactNative#1169] opened 2019-09-02 13:01 UTC
- Your Rocket.Chat Experimental app version: 1.19.0.10977
- Your Rocket.Chat server version: 1.3.2
- Device (or Simulator) you're running with: Samsung S9

Create a channel using the Desktop.

eg testchannel

Go to React App, edit channel to say 'Messing About' and save.

Room Changed to Messing About

Top of screen it still shows 'testchannel' until you go back to the channel list.

Editing channel shows 'messing-about' as the channel name.

**Comment by Prateek93a** [comment] 2019-10-05 12:50
@diegolmello If nobody has taken up this issue, can I work on this?

**Comment by Prateek93a** [comment] 2019-10-08 11:18
@diegolmello Sir, I have fixed the issue, can I raise the PR?

**Comment by diegolmello** [comment] 2019-10-08 12:21
@Prateek93a Don't be shy. You can always open PRs helping us. You don't have to ask :)

**Comment by Prateek93a** [comment] 2019-10-08 12:59
@diegolmello  Ok Sir, thanks.

**Comment by djorkaeffalexandre** [comment] 2020-04-27 20:52
Can't reproduce on latest version, I'll close this.
Thanks.

**Closed by djorkaeffalexandre** 2020-04-27 20:52 UTC
Labels: 🐛 bug
