### ISSUE TITLE
Logic of mention suggestions differs of Web version

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#3681] opened 2022-02-02 08:05 UTC
### Description:

Web client have improved in https://github.com/RocketChat/Rocket.Chat/pull/18309 logic of showing suggestions.
Main concept:

```
This implementation copies the ids of the rooms where the user is part of to inside the user's object allowing direct queries improving the performance in replace of the required lookups. It allows us to list the members of the room first and respect the permissions to prevent users to list non-members.
It doesn't copy the rooms of types d and l since both are largely used and contains few users, so the code uses a different approach for them.

The suggestions follow this order:
The user with the exact username and member of the room
The user with the exact username but not a member of the room (if allowed to list non-members)
The users containing the text in username, name or nickname and member of the room
The users containing the text in username, name or nickname and not a member of the room (if allowed to list non-members)

```
But mobile client now works differently (wrong, IMHO)
It shows users you talked to in DMs recently in suggestions of private chat where no such users.

### Environment Information:

- Rocket.Chat Server Version: 4.3.3
- Rocket.Chat App Version: 4.24.0
- Device Name: iPhone 13
- OS Version: 15.3

### Steps to reproduce:

1. Create private chat with 2 users: `UserA` and yourself
2. Say `Hi!` to few users in DM: `UserB, UserC, UserD`
3. Start typing in chat with `UserA` with symbol `@`
4. There is no `UserA` in suggestions, there is only `UserB, UserC, UserD`, but them not a members of that chat

### Expected behavior:

If user start mention some other user with `@` sign, Web client logic should work. 
First should be users of current chat, then other users from recent conversations.

### Actual behavior:

We discussed that issue with @diegolmello at open server.
Here is a illustrative screenshot
**Mobile version** (after I DM a few user before take a screenshot)
![image](https://user-images.githubusercontent.com/4023037/152115393-06b28d37-c688-4e2d-a118-02712cb8e33b.png)

**Web version** in same chat
![image](https://user-images.githubusercontent.com/4023037/152115509-aacbf462-cfcb-40a6-886c-20f630a87231.png)

### Additional context:

That issue can be fixed in working on other related to mention suggestions and autocomplete issue https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/3342

**Comment by ZathrasXI** [comment] 2022-02-03 14:34
Yes, I am experiencing the same bug. Only on mobile

**The '@' list contains people who are not in the chat**
When I type '@' in a group chat
Then I am presented with a list of the people who are not in the chat. It is a list of the people who I have chatted to recently or have a direct message chat with.

Devices: Galaxy A21S, Fairphone 2

**The '@' list does not contain people who are in the chat even after typing letters from their name**
Given I am in Ged's chat
When I type '@Ged' 
Then Ged does not show up

**Comment by ged** [comment] 2022-02-03 16:41
Except when he *does* show up! ;)

**Comment by ZathrasXI** [comment] 2022-02-04 16:24
@ged solved! ;)

**Comment by ankar84** [comment] 2022-03-30 03:57
> Can you let me know if it would be the correct approach?

Hello, @samay-kothari 
Actually I prefer that web logic was implemented in mobile.
Web logic was introduced here https://github.com/RocketChat/Rocket.Chat/pull/18309

**Comment by samay-kothari** [comment] 2022-03-30 12:20
Okay, I looked into that and this is the preference order, that is specified:
```
The suggestions follow this order:

- The user with the exact username and member of the room
- The user with the exact username but not a member of the room (if allowed to list non-members)
- The users containing the text in username, name or nickname and member of the room
- The users containing the text in username, name or nickname and not a member of the room (if allowed to list non-members

```
I have done some initial work to get the required order and I have some questions, how do we check `if allowed or not allowed to list non-members`?


Also in the initial description of the logic it is specified that `This implementation copies the ids of the rooms where the user is part of to inside the user's object allowing direct queries improving the performance in replace of the required lookups.` I can't get the gist of this, and there is a `_rooms` field in the User model already, so is this thing of copying the roomID to User object is already being implemented?

**Comment by samay-kothari** [comment] 2022-04-02 11:54
Hi @ankar84 
I am able to generate the required order without using the user's object with a different logic (using regex and querying the roomMembers).
Will it work?
Also what exactly is the logic for `if allowed or not allowed to list non-members`? Just need to incorporate that into my implementation.

**Comment by ankar84** [comment] 2022-04-02 13:13
Hey, @samay-kothari and thank you for your work on that issue!!
I'm not a developer and not a part of mobile team, so I can't guide you in technical aspects.
@diegolmello Diego, please help with Samay questions.
Thank you, guys!!

**Comment by samay-kothari** [comment] 2022-04-02 14:01
https://user-images.githubusercontent.com/55805094/161386601-a3e2f6fb-be18-42c3-abfe-a53582ad34ca.mp4
Reproduced the test mentioned above with the changes made.

**Comment by samay-kothari** [comment] 2022-04-02 14:03
https://user-images.githubusercontent.com/55805094/161386718-7f8d2ef1-e418-4b69-8e4a-31a7e9a9df02.mp4
Reproduced the test mentioned above.

**Comment by samay-kothari** [comment] 2022-04-02 14:08
> Hey, @samay-kothari and thank you for your work on that issue!!
You are welcome @ankar84

**Comment by samay-kothari** [comment] 2022-04-04 11:23
Hi @diegolmello 
I looked up the function that is used in the web-app for checking the permission for outside user access, but it uses function `hasAllPermission` which in turn directly call the database collection, can you suggest me a workaround for it?

**Comment by samay-kothari** [comment] 2022-04-06 21:46
hi @gerzonc,
Since this issue is assigned to you can you review my PR and help me with some of doubts mentioned above. There is only one functionality that is left to implement, that is, to list outside members or not. Rest it is working and giving the order as it does in the web-app.

**Closed** 2022-10-31 16:43 UTC
Labels: 👍 improvement
