### ISSUE TITLE
[performance] Update takes to long for users who participates in huge amount of chats

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#3303] opened 2021-07-27 10:26 UTC
### Description:

We have a lot of users that participate on a large amount of different chats.
And when such user launch RCRN application, **Updating...** process takes too long, from 30 seconds to few munities, which is really annoying  for users.

Can that process be improved to take 2 or 5 seconds like WhatsApp or Telegram do?

### Environment Information:

- Rocket.Chat Server Version: 3.16.3
- Rocket.Chat App Version: 4.13.1
- Device Name: Xiaomi Mi 9 SE
- OS Version: Android 11

### Steps to reproduce:

1. Login to RCRN application with user that participating in huge amount of chats
2. Start RCRN application
3. **Updating...** process take too long

### Expected behavior:

**Updating...** process should take less then 5 seconds

### Actual behavior:
![20210727_174005.gif](https://user-images.githubusercontent.com/4023037/127141318-215ee568-d259-4c65-bb47-817ec9b92692.gif)

### Additional context:

WhatsApp and Telegram do that update really fast

**Comment by diegolmello** [comment] 2021-07-27 12:28
Yes, we can take a look soon. I can't reproduce that all the time on open server though. Can you?
Maybe the precise steps are a little bit different?
Wifi vs 4G? Android only? Left the app some time on background? :)

**Comment by ankar84** [comment] 2021-07-28 10:05
> Maybe the precise steps are a little bit different?
> Wifi vs 4G? Android only? Left the app some time on background? :)

I guess you right, Diego!
My bad, I did test on our current whitelabel version, which is on 4.13.1 now

Did some test with latest 4.18.0 version both on open server and my server - all looks perfect. Update... process really as I wanted - about 2-3 seconds.

I prefer to leave that issue open until we build our own RCRN app on 4.18. version and test it.
Thank you, Diego!

**Comment by diegolmello** [comment] 2021-07-28 12:20
Actually, we plan to make it faster.
It can take 10 seconds to connect depending on the app state.

**Comment by ankar84** [comment] 2021-07-28 12:38
> Actually, we plan to make it faster.
> It can take 10 seconds to connect depending on the app state.

That will a really good point of performance improvement, for sure!
Thanks for the mobile team!

**Comment by diegolmello** [comment] 2021-08-11 12:26
That's looks too much imo.
Can you reproduce that on open server?
Thanks!

**Comment by ankar84** [comment] 2021-08-11 13:44
> That's looks too much imo.
> Can you reproduce that on open server?
> Thanks!

No, unfortunately.
I don't have such activities and subscriptions at open server compare to my production server.
But antway, 4.18.0 looks faster then 4.13

**Comment by ankar84** [comment] 2021-08-19 06:09
> I don't have such activities and subscriptions at open server compare to my production server.

I have 1688 subscriptions on my prod server
![image](https://user-images.githubusercontent.com/4023037/130016671-10de5f65-b7b6-4a52-bc2d-7d6884d14fd3.png)

But test 4.19 seems much faster. I will wait it released and give updates here.

**Comment by diegolmello** [comment] 2021-08-19 12:19
I see.
I have more than that on my user on open server :)
Maybe it's a machine thing?

**Comment by ankar84** [comment] 2021-08-19 12:28
> Maybe it's a machine thing?

Could be. I have a pretty powerful Xiaomi Mi 9SE.
And I know, that @wreske have that same issue

**Comment by diegolmello** [comment] 2021-08-19 12:32
I meant machine running the server.
If it keeps happening on 4.19.0, can you add me to your server?

**Comment by ankar84** [comment] 2021-08-19 15:47
> I meant machine running the server.
> If it keeps happening on 4.19.0, can you add me to your server?

Web version don't have such problems.
And now I'm testing 4.19 on my production server, but with test account. And it's really fast! One slow status that I got it was *Waiting for network...* And it was on open server. 
All start application statuses went fats on my server with test account.

I will wait until 4.19 release to check connection on my main account on my production server. And if all will be fast, I will close that issue as solved.

**Comment by ankar84** [comment] 2021-09-01 05:16
I can close that issue only after we build whitelabel application based on 4.19.0 and deep test of it on my server with my main account.

**Comment by aleadco** [comment] 2021-09-01 12:06
> And now I'm testing 4.19 on my production server, but with test account. And it's really fast! One slow status that I got it was *Waiting for network...* And it was on open server.

@ankar84 I have the same perception, if the application just opens, the process is done very quickly (4G and LAN tested).  But if the application is open and the connection to the network is temporarily lost, it remains in the "Waiting for Connection" state for a long time.  I end up closing and opening again so as not to waste time.

**Comment by diegolmello** [comment] 2021-09-01 13:57
Yep. This is something we improved at the beginning of the year, but for sure there's still room for improvement.
It's not that easy to fix though.

**Closed** 2021-09-08 14:02 UTC
Labels: 🐛 bug
