### ISSUE TITLE
App login issue

### ISSUE THREAD

**Issue by t-g-kim** [RocketChat/Rocket.Chat.ReactNative#1375] opened 2019-11-08 14:38 UTC
I installed Rocketchat as a sanp on Ubuntu on an AWS EC2 server.
Loadbalancer <-https ------- nginx ----- rocketchat configuration.

Nginx setting
```
upstream backend {
    server 127.0.0.1:3000;
}

server {
    listen 80;
    server_name allthatsneakers.com;

    # You can increase the limit if your need to.
    client_max_body_size 200M;
    error_log /var/log/nginx/rocketchat.access.log;

    location / {
    proxy_pass http://backend/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;

    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forward-Proto http;
    proxy_set_header X-Nginx-Proxy true;
proxy_redirect off;
    }
}
```
It doesn't work login in app. 
There is no reaction.

**Comment by reetp** [comment] 2019-11-08 14:58
Please read and follow the instructions in the bug template which you have totally ignored:

>**The app isn't connecting to your server?**
> Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

Because this:

![Screenshot_2019-11-08_14-51-14](https://user-images.githubusercontent.com/3800384/68485462-44443900-0237-11ea-8605-e92ebed0cec2.png)

Please close this issue and fix your websockets - this is a configuration, issue not a bug.

Also note this:

> HTTPS Server
> listen 80;

Really? You might want to fix your Nginx config. Please read the documentation

https://rocket.chat/docs/getting-support

**Comment by t-g-kim** [comment] 2019-11-09 01:04
I can't find the answer.

**Comment by reetp** [comment] 2019-11-10 11:53
> I can't find the answer.

This repo is for bugs/issues. Not help.

https://rocket.chat/docs/
https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy/#running-behind-a-nginx-ssl-reverse-proxy

Please close this Issue and follow up as advised - you are not going to get any further assistance here.

**Closed** 2019-11-11 11:52 UTC
