### ISSUE TITLE
The status bar is hard to read 

### ISSUE THREAD

**Issue by superen7527** [RocketChat/Rocket.Chat.ReactNative#5492] opened 2024-01-18 07:46 UTC
Last year's version everything was fine, after upgrading the latest version, the recorded gifs can't be clicked on to play, and the downloads can't be viewed, so I can only return to the message list to see the thumbnails.

source:
去年的版本一切正常，升级最新版以后，记录的gif图无法点击播放，下载也看不了，只能返回到消息列表看缩略图。

**Comment by diegolmello** [comment] 2024-01-18 13:04
What's your app version?
Can you send us a video of what you're trying to report?

**Comment by reinaldonetof** [comment] 2024-01-18 15:09
@superen7527 Are you using Android, right? Is your app updated with the last version 4.45.0?

We fixed that with this PR: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5445

**Comment by reinaldonetof** [comment] 2024-01-18 15:36
> I tried it and it's working fine! 

Awesome, we are glad that was fixed.

>The white status bar text and background on the status bar is still a bit detrimental to seeing the status bar though. Consider it feedback on this issue.

 About this status bar, the issue is duplicated https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/5437. Considering this, I'm closing close this PR.

**Closed by reinaldonetof** 2024-01-18 15:36 UTC
Labels: ℹ️ needs info
