### ISSUE TITLE
Actions buttons problem 

### ISSUE THREAD

**Issue by lucassmacedo** [RocketChat/Rocket.Chat.ReactNative#1137] opened 2019-08-19 20:46 UTC
Hello! I Have a problem when a using buttons with links on "actions", the Android  dont create a LINK on button, when a click nothing happens. But on Chrome works fine. 
I send a message with a API. 

```
{
   "attachments":[
      {
         "title":"[Recursos Humanos] - Claudio Ferrari | Estoquista De Loja | 16 - Caxias do Sul",
         "text":"[Recursos Humanos] - [Claudio Ferrari | Estoquista De Loja | 16 - Caxias do Sul",
         "button_alignment":"horizontal",
         "fields":[
            {
               "short":true,
               "title":"Nome Completo:",
               "value":"Claudio Antonio Ferrari"
            },
            {
               "short":true,
               "title":"Data Admiss\u00e3o",
               "value":"03\/06\/2019"
            },
            {
               "short":true,
               "title":"Cargo",
               "value":"01029-Estoquista De Loja"
            }
         ],
         "actions":[
            {
               "type":"button",
               "text":"Aprovar",
               "color":"#000",
               "url":"https:\/\/portalnovo.test\/rh\/gestao\/devolutiva-exp-status\/13?status=1&notification=fe6078bb-3308-477e-a3f5-846b49807625"
            },
            {
               "type":"button",
               "text":"Reprovar",
               "color":"#888",
               "url":"https:\/\/portalnovo.test\/rh\/gestao\/devolutiva-exp-status\/13?status=0&notification=fe6078bb-3308-477e-a3f5-846b49807625"
            }
         ]
      }
   ],
   "alias":"Portal Drugovich (Mensagem Automática)"
}
```

and on Android the buttons is showing but not working.

![photo5105006752776169521](https://user-images.githubusercontent.com/3357243/63298082-1e973b80-c2a9-11e9-8614-c289bf03b375.jpg)

"On React Native the buttons has not showing" only Rocket.Chat.Android.

**Comment by sampaiodiego** [comment] 2019-08-20 11:28
closing as duplicate of https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/649

**Closed by sampaiodiego** 2019-08-20 11:28 UTC
