### ISSUE TITLE
Rocket.Chat 3.8.1 from Mac AppStore immediatel crashes on launch 

### ISSUE THREAD

**Issue by MattiasMentzer** [RocketChat/Rocket.Chat.ReactNative#4009] opened 2022-04-03 09:15 UTC
### Description:

After updateing Rocket.Chat 3.8.0 to 3.8.1 via the Mac App Store the App crashes everytime on launch.

### Environment Information:

- Rocket.Chat Server Version: 4.5.5
- Rocket.Chat App Version: 3.8.1
- Device Name: MacBook Pro (15-inch, 2018)
- OS Version: macOS Monterey 12.3.1 (21E258)

### Steps to reproduce:

1. Open Rocket.Chat App
2. App crashes immediately 

### Expected behavior:

Normal app launch

### Actual behavior:

crashing

**Comment by MattiasMentzer** [comment] 2022-04-03 09:22
I completely uninstalled it via Appcleaner (from freemacsoft dot net) and reinstalled it via the MAS, it still crashes.

The same version installed via `brew` works fine but I prefer the MAS.

**Comment by ankar84** [comment] 2022-04-04 02:20
duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/2372

**Closed** 2022-04-04 02:23 UTC
