### ISSUE TITLE
GIFs not animated

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat.ReactNative#5288] opened 2023-10-20 22:18 UTC
### Description:

When tapping on the preview of an animated GIF, the image will not be animated.

### Environment Information:

- Rocket.Chat Server Version: 6.4.2
- Rocket.Chat App Version: 4.41.0.49563
- Device Name: ELE-L29 (Huawei P30)
- OS Version: EMUI 12.0.0 (Android 11)

### Steps to reproduce:

1. Open an arbitrary channel in the browser.
2. Create a new message containing an animated GIF, e.g. by using `/tenor` from the Tenor app or by drag-and-dropping an animated GIF from another browser window. When using the latter, ensure that in the upload dialog, the GIF is animated.
3. After submitting the message and waiting for the upload to complete, click on the image in the browser. The image will be enlarged and animated.
4. Change to the app and tap on the very same image there.

### Expected behavior:

The image will be enlarged and animated.

### Actual behavior:

The image will not be animated.

### Additional context:

#4178 describes a different issue regarding GIFs not being animated. However, that issue occurs during file upload. The image then will be static in both browser and app.

**Comment by diegolmello** [comment] 2023-10-27 12:18
@reinaldonetof this is a regression

**Comment by atulsingh98** [comment] 2023-12-17 14:46
hey, was able to replicate this issue. Can i work on this? @diegolmello .Also if you can suggest a optimal way to fix this would be great.

**Comment by reinaldonetof** [comment] 2023-12-18 15:12
Hey @atulsingh98, I suggest that you check this file and method https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/7934141d31dab125c4c4ed75edbc2b0e1e9c40fc/app/lib/methods/handleMediaDownload.ts#L34-L68

There may be an issue with retrieving the file extension.

**Comment by atulsingh98** [comment] 2023-12-20 21:32
@reinaldonetof  yup you're right , looks like there is no case to handle gifs from tenor as its missing mimetype and title whenever the function is invoked. I'll add a fix soon

**Comment by reinaldonetof** [comment] 2023-12-20 22:11
Awesome, congrats!
Let me know, if you have any problem.

**Comment by atulsingh98** [comment] 2023-12-29 06:38
hey @reinaldonetof  , i tried to fix the extension issue but even after that the issue persisted. what did fix the issue was to change the build.gradle file with a few line as suggested here https://reactnative.dev/docs/image#gif-and-webp-support-on-android. So does your pr fix this isuue? or should i make a pr with my changes

https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/47176488/29921378-2d7f-4499-aa6e-81ee52243c83

**Comment by reinaldonetof** [comment] 2023-12-29 18:27
> hey @reinaldonetof , i tried to fix the extension issue but even after that the issue persisted. what did fix the issue was to change the build.gradle file with a few line as suggested here https://reactnative.dev/docs/image#gif-and-webp-support-on-android. So does your pr fix this isuue? or should i make a pr with my changes

Hey @atulsingh98 you were almost there. Yeah, we need to add the `implementation 'com.facebook.fresco:animated-gif:2.5.0'` to animate the gifs, but during the download the file didn't have the mimeType and was downloading locally with a jpg extension. So we must need both fixes. Also, I will add you as a co-author too!

**Comment by atulsingh98** [comment] 2023-12-29 18:41
hey @reinaldonetof  ,thanks  my github email is atulsingh.17is@saividya.ac.in

**Comment by atulsingh98** [comment] 2023-12-30 17:29
Hey @reinaldonetof , i also noticed this issue on ios . i can have a look at that too once your code is merged.

**Closed** 2024-01-03 20:48 UTC
