### ISSUE TITLE
ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by mriedmann** [RocketChat/Rocket.Chat.ReactNative#1938] opened 2020-03-24 17:07 UTC
Hallo!

Currently, we are building and publishing our own (v3.5.1), slightly modified version (only some assets and push notifications) of this RocketChat Client as internal chat-solution. We are really happy with RC so far (thx for providing it!) and would like to continue using it in that way.

Sadly there is a little issue apple is complaining for some time now: 

```
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.
```

I wonder if there is some adaptation in the "official" App to circumvent this issue. Is there anything we could do to make sure that Apple is not rejecting our App in the future? We would really appreciate a comment on that. 

Thank you!

**Comment by phriedrich** [comment] 2020-03-24 17:31
This looks like a duplicate of #1188.

And isn't 3.5.1 also still the "old" version of the app? https://github.com/RocketChat/Rocket.Chat.iOS

**Closed** 2020-03-24 17:54 UTC

**Comment by mriedmann** [comment] 2020-03-24 22:52
Thx for the quick response. Missed that one obviously. Also, it's 4.5.1 of course. 
Sorry for the noise, keep up the good work!

**Comment by ndroo** [comment] 2020-04-01 14:29
Hi folks, looks like this date has now passes and no one can push app updates. Has anyone got a plan to work on this?

**Comment by diegolmello** [comment] 2020-04-01 14:31
This issue is closed. I'll answer you at #1188
