### ISSUE TITLE
E2E encryption not working in android when RESET e2e

### ISSUE THREAD

**Issue by adrastest** [RocketChat/Rocket.Chat.ReactNative#3108] opened 2021-05-04 04:51 UTC
when i want to have encrypted messaging with someone it is working fine for first time.
	but when i forget my E2E password and reset it then the E2E not working in a room and I cant see previouse 
	encrypted messages. is there any solution to see my message after reset my E2E password?

**Comment by johncrisp** [comment] 2021-05-04 08:37
This was asked in open.rocket.chat


Nope. That's the point of public/private key encryption.

If you forget your password to a key you cannot just 'change' it unless you can remember the original. Try say doing it with a ssh key. You have to create a new key pair.

See this link for reference.

https://open.rocket.chat/channel/react-native?msg=ZG98n8ZfzU3ZiWmo1

At best this is a duplicate of this - please search for Issues before opening new ones.

https://github.com/RocketChat/Rocket.Chat/issues/13276#issuecomment-495940581

**Closed by johncrisp** 2021-05-04 08:37 UTC
