### ISSUE TITLE
[BUG] Unable to connect to server using self signed cert

### ISSUE THREAD

**Issue by xgdgsc** [RocketChat/Rocket.Chat.ReactNative#1836] opened 2020-03-06 12:28 UTC
- Your Rocket.Chat Experimental app version: #### 4.4.0 
- Your Rocket.Chat server version: #### 2.4.1
- Device (or Simulator) you're running with: #### Android and ios

Is it possible to support this?
https://stackoverflow.com/questions/36289125/react-native-fetch-from-https-server-with-self-signed-certificate
my url is something like `https://DOMAIN.com:12222/` I tried ios and android import cert but none works.

**Comment by djorkaeffalexandre** [comment] 2020-03-06 13:15
Hey @xgdgsc, can you reach me on `https://open.rocket.chat`?
My username is `djorkaeff.alexandre`.
It should be fixed by #1307.
But let's talk to see what can be your problem.
Thanks.

**Comment by djorkaeffalexandre** [comment] 2020-03-09 12:13
@xgdgsc created a certificate using Lets encrypt and all works fine, maybe it was a mistake with the creation of the self signed certificate.
Closing.

**Closed by djorkaeffalexandre** 2020-03-09 12:13 UTC
Labels: 🐛 bug

**Comment by adrastest** [comment] 2021-02-02 07:02
invalid URL or unable to establish a secure connection
I want to connect from Android rocket chat react native version 4.5.0 to my local rocket chat server but it alert me the above error.
my server is https://10.20.... with self signed certificate.
anyone help me.
thanks in advance

**Comment by diegolmello** [comment] 2021-02-02 13:41
@adrastest we worked on certificate issues on last versions of the app (We're on 4.14.0 now).
Update it and try again.
If the problem persists, open a new issue for you.
Thanks.

**Comment by adrastest** [comment] 2021-02-04 06:26
@diegolmello when i run version (4.14.0) it show me this error
app:installExperimentalPlayDebug?
nay help

**Comment by yash-rajpal** [comment] 2021-02-04 06:30
@adrastest Can you share what commands are you using to run app?

**Comment by adrastest** [comment] 2021-02-04 06:34
I use yarn android

**Comment by yash-rajpal** [comment] 2021-02-04 06:37
Can you share more error logs?

**Comment by adrastest** [comment] 2021-02-04 06:45
@yash-rajpal  I clean the cache and run again it worked but
can not to connect with my local https server which has self signed certificate.

**Comment by yash-rajpal** [comment] 2021-02-04 06:58
What's the problem? Just use your system's IP address and port on which server is running like this

http://IP:port   -> Enter this url when it asks for server url.

**Comment by adrastest** [comment] 2021-02-04 07:09
@yash-rajpal  the problem is when I want to connect rocket chat server via Android rocket chat react native 4.14.0 
it alert me (Java.security.cert.certpahtvalidatorException
trust anchor for certification path not found)
my server is like https://10.20.1.111:5000

**Comment by adrastest** [comment] 2021-02-04 07:12
@yash-rajpal and it is working via http URL but not working with https 
however I install server certificate in Mobile app.

**Comment by adrastest** [comment] 2021-02-24 04:39
@yash-rajpal @diegolmello 
self signed certificate still not solved any new suggestion ?

**Comment by diegolmello** [comment] 2021-02-24 12:19
@adrastest I'm sorry about the silence here, but I asked you to open a new issue if the problem persists https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1836#issuecomment-771642227

Self signed certificate is quite hard for us to be able to help (requires access to server, certificate, user, etc).
What we do every release is to QA on our configured servers.

**Comment by adrastest** [comment] 2021-02-27 05:14
thank you @diegolmello 
I created a new issue( self signed certificate not supported?)
