### ISSUE TITLE
[BUG] User can't change presence status

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#1960] opened 2020-03-31 13:08 UTC
- Your Rocket.Chat Experimental app version: 4.6
- Your Rocket.Chat server version: 3.0.3
- Device (or Simulator) you're running with: iPhone 8

Here you can see, that user presence status is stuck on **Away** and did not change for a while.
![status](https://user-images.githubusercontent.com/4023037/78029721-ba257a00-7369-11ea-80a2-dc5b223b443a.gif)
I saw that bug on Android too.
Often status stuck on **Invisible**, even user did not set it.

**Comment by Prateek93a** [comment] 2020-04-01 10:39
@ankar84 The issue is fixed in the latest version

**Comment by ankar84** [comment] 2020-04-04 12:24
> @ankar84 The issue is fixed in the latest version

@Prateek93a can you clarify by which pr that bug was fixed and in what version?
I think it still persists in 4.6.0.16200

**Comment by Prateek93a** [comment] 2020-04-04 15:44
@ankar84 Hi, sorry I was wrong, I tried to reproduce the error earlier but couldn't reproduce it but now after updating the branch, I am able to reproduce the error. The presence status is not changing. Can you open the issue again? Thanks

**Comment by ankar84** [comment] 2020-04-04 15:57
> Can you open the issue again?

No, unfortunately, I can't.
@diegolmello please reopen that issue

**Comment by ankar84** [comment] 2020-04-04 16:02
Now I did reproduce that bug on 4.6.0.16200 with my local server version 3.0.3
1. Open app, check status - it's ok
2. Minimize app
3. Clear memory
4. Open app
5. You get offline status (or invisible)
6. Try to change status - you can't

**Comment by ankar84** [comment] 2020-04-04 16:09
Just tested with open.rocket.chat and behaviour a little bit different. When you reopen app, you status online and you can't change it.
![Rocket](https://user-images.githubusercontent.com/4023037/78455584-63050980-76c9-11ea-9cb7-026d177411d2.gif)

**Closed** 2020-04-06 19:32 UTC

**Comment by ankar84** [comment] 2020-04-07 14:20
4.6.1 fixed that bug! Thanks a lot!
