### ISSUE TITLE
Read channels on desktop appear to be unread in mobile app

### ISSUE THREAD

**Issue by zdumitru** [RocketChat/Rocket.Chat.ReactNative#2762] opened 2021-01-05 12:32 UTC
### Environment Information:

- Rocket.Chat Server Version: 3.9.3
- Rocket.Chat App Version: 4.13.0.22100
- Device Name: Samsung S20
- OS Version: Android 11

### Steps to reproduce:
Prerequisites - Be logged in at open.rocket.chat in the browser on computer and logged in on mobile app for the same server.

1. Open mobile app with unread channels on top (for me it was 4 in total)
2. Click back button (<) OR home button (□) on Android app to make the app close/disappear
3. In computer browser go to rocket chat server.
4. In computer browser read all the messages in one of the channels (e.g. `dev`). Make sure that the `dev` channel is no longer bold, meaning it doesn't have any unread messages.
5. Close the browser - this step is optional
6. On mobile phone click on the icon with Rocket Chat to make the app open again
7. See that `dev` channel appears again on top in the unread channels section

### Expected behavior:

`dev` channel does not appear in the list of unread channels and is moved to the read channels list instead.

### Actual behavior:

Channel that has been read in browser still appears as unread on mobile app.

### Additional context:

When manually refreshing the list (swipe down) on mobile app, the channel is moved below to the read list of channels.

#2660 has been closed and I expanded steps that need to be taken in order to reproduce it

**Comment by diegolmello** [comment] 2021-01-05 17:11
@zdumitru Can you try on 4.13.1.22189?
It just landed Google Play (waiting Apple review for iOS one).
I tried here and couldn't reproduce it.
Thanks!

**Comment by zdumitru** [comment] 2021-01-05 17:24
@diegolmello Yes, looks fixed in the latest update that I just received - `4.13.1.22189`.

**Comment by diegolmello** [comment] 2021-01-05 17:25
Awesome!
Let me know if it happens again.
We can reopen this issue if needed.
Thank you.

**Comment by zdumitru** [comment] 2021-01-06 22:37
@diegolmello It started hapenning again, even though nothing was changed.

**Comment by diegolmello** [comment] 2021-01-07 11:57
Ok, let's reopen.
This might fix it https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2765
I'll try to release it as 4.14.0 on Experimental later today.

**Comment by zdumitru** [comment] 2021-01-19 12:46
@diegolmello This also happens the other way around. Just read all the chats on mobile (everything is read and not bold) and then opened web version in browser - three unread channels.

Let me know if you need screenshots, reproduction steps or anything else to fix it.

**Comment by diegolmello** [comment] 2021-01-19 12:48
@zdumitru Interesting. Please, send us some screenshots.

**Comment by zdumitru** [comment] 2021-01-19 13:02
@diegolmello 
1. All chats are marked as read in the RC app - version 4.14.0.22464. No bold channels or PMs (unread are on top). To confirm that, refreshed the view by swiping finger from top to bottom on the screen.
![Screenshot_20210119-135135_RocketChat Experimental](https://user-images.githubusercontent.com/11751017/105037593-7f0e4780-5a5e-11eb-8db0-d6f173ea0d0f.jpg)

2.  Opened open.rocket.chat in browser - three unread channels. Refreshed the page with F5, also with CTRL+R, also with CTRL+SHIFT+R and no change. Still see 3 unread channels.
![FireShot Capture 017 - Rocket Chat - open rocket chat](https://user-images.githubusercontent.com/11751017/105037656-98af8f00-5a5e-11eb-9859-fc9329bbcc45.png)

Also have two things opened at the same time - the app and web version. No unread messages in the app and 3 unread channels in web version. Can take a picture of them together if you want.

**Comment by diegolmello** [comment] 2021-01-19 13:12
@zdumitru Cool, but that doesn't exclude it from still being an issue on the mobile app, as we can't see any of the unread channels on the mobile app.

- Can you scroll to #dev channel on mobile app and check if it's unread?
- Can you tap `Settings > Clear local server cache` tell me what happens?

**Comment by zdumitru** [comment] 2021-01-19 13:31
@diegolmello 
* dev channel on mobile is read. This is what I saw when I opened it.
![Screenshot_20210119-142815_RocketChat Experimental](https://user-images.githubusercontent.com/11751017/105041054-d44c5800-5a62-11eb-9f32-d21f187f0c44.jpg)

* When I cleared local server cache it still showed #dev and all other channels read. So nothing changed here.

**Comment by diegolmello** [comment] 2021-01-19 13:33
Ok.
Let me know if you're seeing it often or if you manage to get a reproducible example.
Thanks.

**Closed** 2023-01-20 16:40 UTC
Labels: 🐛 bug, ℹ️ needs info
