### ISSUE TITLE
Cant build Android App

### ISSUE THREAD

**Issue by WreckingBANG** [RocketChat/Rocket.Chat.ReactNative#4217] opened 2022-05-25 05:16 UTC
Hi i was trying to build the android apk without any changes done to it.
I am using android studio.

I am getting this error:

`: Build completed with 8 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkE2eFossDebugAarMetadata'.
> Could not resolve all files for configuration ':app:e2eFossDebugRuntimeClasspath'.
   > Could not find org.jitsi.react:jitsi-meet-sdk:3.6.0-libre.
     Searched in the following locations:
       - file:/C:/Users/Danie/.m2/repository/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/react-native/android/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/jsc-android/dist/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/detox/Detox-android/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - https://github.com/RocketChat/jitsi-maven-repository/raw/libre/releases/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - https://dl.google.com/dl/android/maven2/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - https://jcenter.bintray.com/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - https://maven.google.com/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
     Required by:
         project :app > project :react-native-jitsi-meet
   > Could not find com.github.yalantis:ucrop:2.2.6-native.
     Searched in the following locations:
       - file:/C:/Users/Danie/.m2/repository/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/react-native/android/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/jsc-android/dist/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/detox/Detox-android/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://github.com/RocketChat/jitsi-maven-repository/raw/libre/releases/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://dl.google.com/dl/android/maven2/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://jcenter.bintray.com/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://maven.google.com/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
     Required by:
         project :app > project :react-native-image-crop-picker

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeE2eFossDebugAssets'.
> Could not resolve all files for configuration ':app:e2eFossDebugRuntimeClasspath'.
   > Could not find org.jitsi.react:jitsi-meet-sdk:3.6.0-libre.
     Searched in the following locations:
       - file:/C:/Users/Danie/.m2/repository/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/react-native/android/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/jsc-android/dist/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/detox/Detox-android/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - https://github.com/RocketChat/jitsi-maven-repository/raw/libre/releases/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - https://dl.google.com/dl/android/maven2/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - https://jcenter.bintray.com/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - https://maven.google.com/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
     Required by:
         project :app > project :react-native-jitsi-meet
   > Could not find com.github.yalantis:ucrop:2.2.6-native.
     Searched in the following locations:
       - file:/C:/Users/Danie/.m2/repository/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/react-native/android/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/jsc-android/dist/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/detox/Detox-android/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://github.com/RocketChat/jitsi-maven-repository/raw/libre/releases/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://dl.google.com/dl/android/maven2/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://jcenter.bintray.com/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://maven.google.com/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
     Required by:
         project :app > project :react-native-image-crop-picker

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processE2eFossDebugMainManifest'.
> Could not resolve all files for configuration ':app:e2eFossDebugRuntimeClasspath'.
   > Could not find org.jitsi.react:jitsi-meet-sdk:3.6.0-libre.
     Searched in the following locations:
       - file:/C:/Users/Danie/.m2/repository/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/react-native/android/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/jsc-android/dist/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/detox/Detox-android/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - https://github.com/RocketChat/jitsi-maven-repository/raw/libre/releases/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - https://dl.google.com/dl/android/maven2/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - https://jcenter.bintray.com/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - https://maven.google.com/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
     Required by:
         project :app > project :react-native-jitsi-meet
   > Could not find com.github.yalantis:ucrop:2.2.6-native.
     Searched in the following locations:
       - file:/C:/Users/Danie/.m2/repository/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/react-native/android/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/jsc-android/dist/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/detox/Detox-android/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://github.com/RocketChat/jitsi-maven-repository/raw/libre/releases/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://dl.google.com/dl/android/maven2/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://jcenter.bintray.com/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://maven.google.com/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
     Required by:
         project :app > project :react-native-image-crop-picker

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

4: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-image-crop-picker:generateDebugRFile'.
> Could not resolve all files for configuration ':react-native-image-crop-picker:debugCompileClasspath'.
   > Could not find com.github.yalantis:ucrop:2.2.6-native.
     Required by:
         project :react-native-image-crop-picker

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

5: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-jitsi-meet:generateDebugRFile'.
> Could not resolve all files for configuration ':react-native-jitsi-meet:debugCompileClasspath'.
   > Could not find org.jitsi.react:jitsi-meet-sdk:3.6.0-libre.
     Required by:
         project :react-native-jitsi-meet

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

6: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkE2eFossDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:e2eFossDebugRuntimeClasspath'.
   > Could not find org.jitsi.react:jitsi-meet-sdk:3.6.0-libre.
     Searched in the following locations:
       - file:/C:/Users/Danie/.m2/repository/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/react-native/android/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/jsc-android/dist/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/detox/Detox-android/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - https://github.com/RocketChat/jitsi-maven-repository/raw/libre/releases/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - https://dl.google.com/dl/android/maven2/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - https://jcenter.bintray.com/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - https://maven.google.com/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
     Required by:
         project :app > project :react-native-jitsi-meet
   > Could not find com.github.yalantis:ucrop:2.2.6-native.
     Searched in the following locations:
       - file:/C:/Users/Danie/.m2/repository/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/react-native/android/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/jsc-android/dist/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/detox/Detox-android/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://github.com/RocketChat/jitsi-maven-repository/raw/libre/releases/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://dl.google.com/dl/android/maven2/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://jcenter.bintray.com/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://maven.google.com/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
     Required by:
         project :app > project :react-native-image-crop-picker

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get moreproject :app > project :react-native-image-crop-picker

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

7: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:desugarE2eFossDebugFileDependencies'.
> Could not resolve all files for configuration ':app:e2eFossDebugRuntimeClasspath'.
   > Could not find org.jitsi.react:jitsi-meet-sdk:3.6.0-libre.
     Searched in the following locations:
       - file:/C:/Users/Danie/.m2/repository/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/react-native/android/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/jsc-android/dist/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/detox/Detox-android/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - https://github.com/RocketChat/jitsi-maven-repository/raw/libre/releases/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - https://dl.google.com/dl/android/maven2/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - https://jcenter.bintray.com/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - https://maven.google.com/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
     Required by:
         project :app > project :react-native-jitsi-meet
   > Could not find com.github.yalantis:ucrop:2.2.6-native.
     Searched in the following locations:
       - file:/C:/Users/Danie/.m2/repository/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/react-native/android/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/jsc-android/dist/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/detox/Detox-android/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://github.com/RocketChat/jitsi-maven-repository/raw/libre/releases/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://dl.google.com/dl/android/maven2/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://jcenter.bintray.com/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://maven.google.com/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
     Required by:
         project :app > project :react-native-image-crop-picker

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

8: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeE2eFossDebugNativeLibs'.
> Could not resolve all files for configuration ':app:e2eFossDebugRuntimeClasspath'.
   > Could not find org.jitsi.react:jitsi-meet-sdk:3.6.0-libre.
     Searched in the following locations:
       - file:/C:/Users/Danie/.m2/repository/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/react-native/android/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/jsc-android/dist/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/detox/Detox-android/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - https://github.com/RocketChat/jitsi-maven-repository/raw/libre/releases/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - https://dl.google.com/dl/android/maven2/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - https://jcenter.bintray.com/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
       - https://maven.google.com/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom
     Required by:
         project :app > project :react-native-jitsi-meet
   > Could not find com.github.yalantis:ucrop:2.2.6-native.
     Searched in the following locations:
       - file:/C:/Users/Danie/.m2/repository/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/react-native/android/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/jsc-android/dist/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - file:/C:/Users/Danie/mobile-projects/Rocket.Chat.ReactNative/node_modules/detox/Detox-android/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://github.com/RocketChat/jitsi-maven-repository/raw/libre/releases/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://dl.google.com/dl/android/maven2/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://jcenter.bintray.com/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
       - https://maven.google.com/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom
     Required by:
         project :app > project :react-native-image-crop-picker

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 36s
992 actionable tasks: 13 executed, 979 up-to-date`

**Comment by diegolmello** [comment] 2022-05-25 13:09
Duplicate of https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/3548#issuecomment-1057163366

**Closed by diegolmello** 2022-05-25 13:09 UTC
