### ISSUE TITLE
Can't save pictures on Android 10

### ISSUE THREAD

**Issue by johnypeterson** [RocketChat/Rocket.Chat.ReactNative#2456] opened 2020-09-10 11:36 UTC
### Description:

Android 10 devices get an error while trying to save pictures from chat. Looks like an album creation fails https://github.com/react-native-community/react-native-cameraroll/issues/115

### Environment Information:

- Rocket.Chat Server Version: 3.6.0
- Rocket.Chat App Version: 4.10.0
- OS Version: Android 10

### Steps to reproduce:

1. Go to any room which has messages with pictures
2. Open the picture and click the download button
3. Give the permission to access media on your device

### Expected behavior:

The picture should be saved to the device's gallery 

### Actual behavior:
![Screenshot_2020-09-10-11-46-56-997_com autoxloo wx chat 1](https://user-images.githubusercontent.com/58329905/92723840-540a3d80-f372-11ea-9519-3dbf76536615.jpg)

Error while saving the picture

**Comment by shobhi1310** [comment] 2020-09-11 18:01
I would like to contribute to this bug, and I am also a first timer on open-source. 🙄

**Comment by diegolmello** [comment] 2020-09-11 18:47
@shobhi1310 Thanks, but we're working on a fix already.
There're other issues on [good first issue label](https://github.com/RocketChat/Rocket.Chat.ReactNative/labels/%F0%9F%8D%AD%20good%20first%20issue)

**Comment by shobhi1310** [comment] 2020-09-12 04:31
Thanks!, I will look into those issues then.

**Comment by ankar84** [comment] 2020-10-05 07:48
My Xiaomi Mi 9 SE is on Android 10 QkQ1.190828.002
I did try couple versions - 4.7 and latest 4.11 - all fine, pictures was saved

**Comment by Scorpio92** [comment] 2020-10-19 01:40
The problem is urgent.
I have compiled the application from the latest source code (master, develop, single-server) the problem is available. I downloaded assembly 4.11 from the application store - there is a problem.
Asus ZenFone6, Android 10 (Stock ROM).

**Comment by ankar84** [comment] 2020-10-19 02:17
> The problem is urgent.
> I have compiled the application from the latest source code (master, develop, single-server) the problem is available. I downloaded assembly 4.11 from the application store - there is a problem.
> Asus ZenFone6, Android 10 (Stock ROM).

Please show permissions granted to RCRN app.

**Comment by Scorpio92** [comment] 2020-10-19 02:39
![1](https://user-images.githubusercontent.com/2156216/96395520-2ed9dc00-1208-11eb-83d5-0efce9295076.jpg)

**Comment by Scorpio92** [comment] 2020-10-19 02:51
> > The problem is urgent.
> > I have compiled the application from the latest source code (master, develop, single-server) the problem is available. I downloaded assembly 4.11 from the application store - there is a problem.
> > Asus ZenFone6, Android 10 (Stock ROM).
> 
> Please show permissions granted to RCRN app.

Storage is permited.

![1](https://user-images.githubusercontent.com/2156216/96395520-2ed9dc00-1208-11eb-83d5-0efce9295076.jpg)

**Comment by ankar84** [comment] 2020-10-19 04:01
> Storage is permited.

It's still somehow device or vendor related
![Screenshot_2020-10-19-11-00-08-885_com google android permissioncontroller](https://user-images.githubusercontent.com/4023037/96400247-72c5e480-11fa-11eb-9c0e-fd1f06673a48.jpg)
![Screenshot_2020-10-19-10-59-51-682_chat rocket reactnative](https://user-images.githubusercontent.com/4023037/96400251-73f71180-11fa-11eb-9fc3-ec0b92374383.jpg)

**Comment by diegolmello** [comment] 2020-10-19 11:54
> The problem is urgent.
> I have compiled the application from the latest source code (master, develop, single-server) the problem is available. I downloaded assembly 4.11 from the application store - there is a problem.
> Asus ZenFone6, Android 10 (Stock ROM).

@Scorpio92 Contributions appreciated.

**Comment by Scorpio92** [comment] 2020-10-20 01:34
samsung s10e, Android 10, same problem.

**Comment by AgentTNT** [comment] 2020-10-31 20:02
@diegolmello 

This issue was introduced via https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2375, which would have broken version 4.10 and beyond for Android.

The fix is to opt out of scoped storage (https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage)

`android:requestLegacyExternalStorage="true"`

This is important to note for future changes to the targetSDK, as this workaround is no longer valid for 30+. You will need to follow this (https://developer.android.com/training/data-storage/use-cases#migrate-legacy-storage) to target anything further than you already are. 

After setting the flag in the manifest, the only thing that I have noticed in terms of odd behavior is what the files are called, as they change once saved to gallery, as it no longer preserves the source name. 

What is unexplainable is why some Android 10 devices mentioned above work just fine, and others just don't. Despite that unknown, saving images on my Note 20 have started working once again while debugging. The odd thing was in the emulator, it always worked to save the image (Android 11), even prior to making that change based on the 4.11.0 branch. 

Please add to the 4.12.0 code that you are currently testing, and let's restore a functionality thats been broken for near 2 months.

**Comment by Scorpio92** [comment] 2020-11-03 12:24
> @diegolmello
> 
> This issue was introduced via #2375, which would have broken version 4.10 and beyond for Android.
> 
> The fix is to opt out of scoped storage (https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage)
> 
> `android:requestLegacyExternalStorage="true"`
> 
> This is important to note for future changes to the targetSDK, as this workaround is no longer valid for 30+. You will need to follow this (https://developer.android.com/training/data-storage/use-cases#migrate-legacy-storage) to target anything further than you already are.
> 
> After setting the flag in the manifest, the only thing that I have noticed in terms of odd behavior is what the files are called, as they change once saved to gallery, as it no longer preserves the source name.
> 
> What is unexplainable is why some Android 10 devices mentioned above work just fine, and others just don't. Despite that unknown, saving images on my Note 20 have started working once again while debugging. The odd thing was in the emulator, it always worked to save the image (Android 11), even prior to making that change based on the 4.11.0 branch.
> 
> Please add to the 4.12.0 code that you are currently testing, and let's restore a functionality thats been broken for near 2 months.

It's works. Thanks!

**Closed** 2020-11-17 17:53 UTC
Labels: 🐛 bug
