### ISSUE TITLE
Rocketchat reactnative client stuck at "updating" 

### ISSUE THREAD

**Issue by Arska777** [RocketChat/Rocket.Chat.ReactNative#3169] opened 2021-05-28 06:26 UTC
### Description:

Rocketchat Reactnative app is stuck in the "updating" state by just using the client
The "updating" text is seen at the top of the appilication screen below the RocketChat server name
As a result the contents of the chat rooms are not updated correctly and no new message notifications gets through.
When opening the chat room the client will show just partial contents of the chat room and any messages 
that cannot be retrieved are not displayed at all. Only "circulating icon" is seen instead  
This renders the client totally unusable

This may be related to the network connection changes. When this was seen the device had disconnected
from Wifi and started to use mobile data and later returned back to Wifi. 
The app was displaying "no network connection" for some time despite the network connection was working well

The "updating" issue can be temporarily fixed by cleaning local cache. This will not fix this problem permanently though.

### Environment Information:

- Rocket.Chat Server Version: 3.14.0
- Rocket.Chat App Version: 4.16.2.23909
- Device Name: Huawei P20 Pro
- OS Version: Android 10

### Steps to reproduce:

1. Just use the client
2.  Enventually it will start to display "updating" at the top of the screen

### Expected behavior:

 The app works ok 

### Actual behavior:

The app shows "updating" text at the top of the app below the server details

**Comment by johncrisp** [comment] 2021-06-06 21:40
Hi.

First, please upgrade to 3.14.4 - see the release page and changelog.

> This may be related to the network connection changes. When this was seen the device had disconnected
from Wifi and started to use mobile data and later returned back to Wifi.

Quite probably as it re-establishes a websocket.

Make sure you network connections are working well and your proxy is working correctly - these are the usual sources of  'updating' issues.

**Comment by Arska777** [comment] 2021-06-08 10:44
Hi,
I could not find any references in the 3.14.4 (or latest 3.14.5) Rocket.Chat server release notes that would indicate any fixes to this reported problem. Anyway I have upgraded our internal server to release 3.4.15 and continue using the system. If this problem reoccurs I will let you know. 
-Ari

**Comment by ahampro** [comment] 2021-07-28 15:49
@Arska777 has the issue been resolved by the update or not resolved yet?

**Comment by jalbstmeijer** [comment] 2021-09-07 07:44
Same issue here.

Have just started using the Rocket.Chat.ReactNative for two days now, but have seen this "stays in updating state" issue twice already.
First time I forced stopped the app to solve the issue. Second time I got an "alert icon" behind my new message. After  "Clear local server cache" this time it worked again.

android: 11 (Oxygen OS 11.0.8.8.IN21BA)
client: 4.19.0.25555
server: 3.18.0 (self hosted)

Gr, J

**Comment by emikolajczak** [comment] 2021-09-08 06:48
Hi,
I can confirm that this problem also rise my users.

**Comment by ankar84** [comment] 2021-09-08 06:56
I see that issue from time to time, but not so often at 4.19.0
Proper steps to reproduce are unknown.

**Comment by diegolmello** [comment] 2021-09-08 12:38
That's something we plan to fix asap, but we need all the info available.
So send us steps to reproduce it.
From my understanding, this issue happens when:
- the app is sent to background and stays there for some time
- connection might have changed (e.g. from wi-fi to 4g)
- app is restored
- the app has a socket connection in unknown state

Is this what you're experiencing?

**Comment by emikolajczak** [comment] 2021-09-08 12:41
> That's something we plan to fix asap, but we need all the info available.
> So send us steps to reproduce it.
> From my understanding, this issue happens when:
> 
> * the app is sent to background and stays there for some time
> * connection might have changed (e.g. from wi-fi to 4g)
> * app is restored
> * the app has a socket connection in unknown state
> 
> Is this what you're experiencing?

Yes, I think it is the basic way to try reproduce. But as Anton said occurs from time to time.

**Comment by jalbstmeijer** [comment] 2021-09-09 08:01
Hi,

Found the chat app in this state again this morning.
Another observation, very selectively incoming messages come through.
Outgoing messages all get the triangle alert icon.
I left the app running and tried to collect some Android logs. I filtered them by the string "rocky".

In the meantime the app has been in this "updating" state for more than an hour already.

Please explain which logs you need and how to collect them of these are not usable.

Gr, Justin
[logs.zip](https://github.com/RocketChat/Rocket.Chat.ReactNative/files/7134608/logs.zip)

**Comment by diegolmello** [comment] 2021-09-09 12:01
@jalbstmeijer We don't have logs for this.
So you left the app in background, went to sleep and opened it this morning.
Is that correct?

> Outgoing messages all get the triangle alert icon.

That's a collateral effect of the `updating` state.
What happens is that the app couldn't establish a connection to the server, so any requests fail.

**Comment by jalbstmeijer** [comment] 2021-09-09 12:41
> @jalbstmeijer We don't have logs for this.
> So you left the app in background, went to sleep and opened it this morning.
> Is that correct?

Correct.

**Comment by ankar84** [comment] 2021-09-24 03:40
I'm currently on 4.19.0 for my main account and can tell that saw `Updating...` status for about 15 seconds. It's definitely much better then it was before, but still need to be improved.
Also I saw loop with `Connecting..` <=> `Waiting for network...` statuses about 2-3 times, then app connected successfully.

**Comment by jalbstmeijer** [comment] 2021-12-02 10:43
Still have seen this issue with server 4.1.2 and client 4.22.
If there is anything I can do to debug? please let me know.

In the meantime running server 4.2.0, I'll report if I encounter it with that version too.

**Comment by ankar84** [comment] 2021-12-02 10:49
> Still have seen this issue with server 4.1.2 and client 4.22. If there is anything I can do to debug? please let me know.
> 
> In the meantime running server 4.2.0, I'll report if I encounter it with that version too.

I guess something can change when https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3531 merged. I hope!

**Closed** 2021-12-07 20:05 UTC

**Comment by jalbstmeijer** [comment] 2021-12-28 10:11
Hi,

Connections seem smoother, but unfortunately the issue is still there for me.

server:  4.2.1
client: 4.23.0

The issue looks a bit different since client 4.23.0.
In the chats overview nothing indicates a connection is still being initiated, but when sending  a message I get the red alert icon.
Going back to the  chats overviews, it is and stays in updating state.

I need to clear the client cache to get it to work again.

Please let me know if and how to collected any useful debug information.

Gr, J

**Comment by jalbstmeijer** [comment] 2022-01-03 16:55
Hi,

Although it is probably a client issue, I'll keep updating the ticket when server or client version gets updated.

Still seeing the issue.

server: 4.3.0
client: 4.23.0

Gr, J

**Comment by jalbstmeijer** [comment] 2022-01-10 13:47
Hi,

Any chance we can re-open ticket issue?

Gr, J

**Comment by jalbstmeijer** [comment] 2022-01-29 14:15
Hi,

Still seeing the issue with server 4.3.2 and client 4.24.

It might be a web-sockets issue in combination with Traefik 1.7.

https://forums.rocket.chat/t/android-mobile-client-stuck-on-updating/11330/2

Any suggestion?

Gr, J

**Comment by jalbstmeijer** [comment] 2022-03-07 07:07
Tried Traefik v2, with the same result. So I'm a bit stuck.
 Any suggestion how to debug further?

**Comment by diegolmello** [comment] 2022-03-07 13:27
https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3815

**Comment by jalbstmeijer** [comment] 2022-03-08 16:29
> #3815

Yes my hopes were first with #3531, but that did nothing to improve the situation.
Lately is even become more unstable. Where before it was clear the app was hanging in updating state and cleaning cache was enough to get it to work again. Now the state is sometimes not clear and when it hangs sending an image I have had already several times that even clearing cache hangs and I need to forcefully close the app to get it working again.

It feels much more efficient if the client could tell us what is going wrong. Maybe by distributing a client version with debug options. Now I feel we are just guessing what is going on.

**Comment by jalbstmeijer** [comment] 2022-03-30 10:26
@diegolmello 

Issue remained after the Android client release 4.26 on my self hosted server version 4.5.4.

Please let me know what I can do to pinpoint the issue.

I'm happy to provide a test account for instance.

**Comment by feriferdinan** [comment] 2022-06-06 13:14
Please open this issue, because i still got same problem

**Comment by antgel** [comment] 2022-06-10 12:05
This could be a duplicate of #4012. I turned off HTTP/2 on the nginx reverse proxy (great "solution") and the problem went away.
