### ISSUE TITLE
Message details not shown in push notifications anymore

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat.ReactNative#5496] opened 2024-01-18 23:08 UTC
### Description:

The notifications on my Android phone do not show any message details anymore, just the text "You have a new message", despite the server being configured to deliver message details.

### Environment Information:

- Rocket.Chat Server Version: 3.5.3
- Rocket.Chat App Version: 4.45.0.55377
- Device Name: ELE-L29 (Huawei P30)
- OS Version: EMUI 12.0.0 (Android 11)

### Steps to reproduce:

1. Configure the server like this (Workspace -> Settings -> Push -> Privacy):

![Clipboard - January 18, 2024 23_19](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/404840/17ff0c80-fb48-4a5c-9a14-9505315c6936)

2. Wait for a push notification being shown on your mobile phone.

### Expected behavior:

The message is shown on the push notification, including its details.

### Actual behavior:

The push notification does not contain any message details:

![Screenshot_20240118_231842](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/404840/d34940ce-e5c2-4c82-98b1-b01010aaf9ea)

### Additional context:

This issue is quite new, it must have been introduced in one of the most recent versions of the Rocket.Chat server or the app.

**Comment by preeesha** [comment] 2024-01-23 11:07
Hey @paulchen, thanks for pointing out the issue

@GleidsonDaniel, can I work on this issue? My approach will be to first verify whether the issue belongs to this repository or the primary mono repo of Rocket.Chat. If this issue is in the app only then I will dive into the notification pushing process and update you with results.

Thanks for your time and consideration
Prisha Gupta

**Comment by GleidsonDaniel** [comment] 2024-01-23 11:49
> Hey @paulchen, thanks for pointing out the issue
> 
> @GleidsonDaniel, can I work on this issue? My approach will be to first verify whether the issue belongs to this repository or the primary mono repo of Rocket.Chat. If this issue is in the app only then I will dive into the notification pushing process and update you with results.
> 
> Thanks for your time and consideration Prisha Gupta

I don't recommend working on this issue.
The notification flow is a very complex flow, and we are already working on this issue internally.

**Comment by GleidsonDaniel** [comment] 2024-01-24 16:36
Hey @paulchen, can you find out if this happened after updating the app or the server?
Because testing here on some servers, I realized that the problem is intermittent, showing that the problem is not really in the mobile app, because if it were on the mobile it wouldn't work any of the time.
On a private server (with very few users) with these same settings it worked 100% of the time.

I'm waiting for more information.

**Comment by paulchen** [comment] 2024-01-24 21:10
> Hey @paulchen, can you find out if this happened after updating the app or the server?

I noticed the problem on Jan 19 in the evening. The app on my mobile phone was last updated on Jan 16.

There was no update to the server on Jan 19, but I restarted the instance twice earlier that day (due to updating MongoDB from 6.0.12 to 6.0.13 and later Docker from 24.0.7 to 25.0.0). However, all the messages that triggered the problem were sent at a later time.

> Because testing here on some servers, I realized that the problem is intermittent, showing that the problem is not really in the mobile app, because if it were on the mobile it wouldn't work any of the time.

Since I reported the issue, I have received some notifications that worked as expected while others didn't.

> On a private server (with very few users) with these same settings it worked 100% of the time.

My instance is a small instance on the Starter plan with 18 registered users.

**Comment by loopway** [comment] 2024-01-25 14:43
similar situation here: updated rocket.chat server (starter) on January 11 from 6.4.0 to 6.5.2 (and mongodb from 4.4.21 to 6.0.12). ios app got updated on January 17 to 4.45.0. all but one (!) push notifications did not show details.

**Comment by GleidsonDaniel** [comment] 2024-01-25 17:07
> similar situation here: updated rocket.chat server (starter) on January 11 from 6.4.0 to 6.5.2 (and mongodb from 4.4.21 to 6.0.12). ios app got updated on January 17 to 4.45.0. all but one (!) push notifications did not show details.

Are you having this error on iOS too?
Or is your device Android?

**Comment by loopway** [comment] 2024-01-29 20:39
https://github.com/RocketChat/Rocket.Chat/issues/31493 - might be the same problem.

**Comment by MjStar24** [comment] 2024-02-02 18:56
I would like to resolve this issue

**Comment by Vaxter** [comment] 2024-02-15 10:44
> > similar situation here: updated rocket.chat server (starter) on January 11 from 6.4.0 to 6.5.2 (and mongodb from 4.4.21 to 6.0.12). ios app got updated on January 17 to 4.45.0. all but one (!) push notifications did not show details.
> 
> Are you having this error on iOS too? Or is your device Android?

I do have the same issue on iOS, both on iPad and iPhone.

**Comment by matbgn** [comment] 2024-02-16 08:01
Same problem here. This started from the day we bumped Rocket.Chat Server from version 6.4.X to 6.5.X

**Comment by 0ki** [comment] 2024-02-16 11:18
Same. After upgrade to 6.5 notification text disappeared. Any way to debug?

**Comment by diegolmello** [comment] 2024-02-16 16:25
FYI we've been investigating this issue.

In the meantime, can you create an account and see if push notifications are working as expected on https://open.rocket.chat? It's our community server and [secured push notification](https://docs.rocket.chat/use-rocket.chat/rocket.chat-mobile/push-notifications/secured-push-notification#fetch-full-message-content-from-the-server-on-the-receipt) is enabled there.

**Comment by matheusbsilva137** [comment] 2024-02-19 16:27
@paulchen are you also using the Starter plan on your workspace? Or is it running a Pro/Enterprise license?
You can check this in **Workspace > Administration > Subscription**.

**Comment by paulchen** [comment] 2024-02-19 16:30
> @paulchen are you also using the Starter plan on your workspace? Or is it running a Pro/Enterprise license? You can check this in **Workspace > Administration > Subscription**.

Starter plan.

However, in the recent days I have not encountered the problem.

**Comment by matbgn** [comment] 2024-02-20 10:56
Error still happening on iOS for information

**Comment by 0ki** [comment] 2024-02-27 07:39
Just started working today randomly. No update to app, nor the server.

**Comment by Vaxter** [comment] 2024-02-27 08:42
Same for me a couple of days ago, but it’s Really random.
Some notifications have preview, and some don’t.

**Comment by diegolmello** [comment] 2024-02-27 20:22
I have a possible fix on https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5596
But I need help testing from all of you, @paulchen @loopway @Vaxter @matbgn @0ki .

Here's the link to TestFlight https://testflight.apple.com/join/3gcYeoMr
Build version should be 4.47.0.58428.

Thanks!
Let me know if you have any questions.

**Comment by paulchen** [comment] 2024-02-27 20:29
> Here's the link to TestFlight https://testflight.apple.com/join/3gcYeoMr Build version should be 4.47.0.58428.

Unfortunately, I'm unable to use TestFlight.

> * Device Name: ELE-L29 (Huawei P30)
> * OS Version: EMUI 12.0.0 (Android 11)

**Comment by diegolmello** [comment] 2024-02-27 20:39
@paulchen I wasn't able to reproduce the issue on Android at all.
Let me know if it happens again.

**Comment by matbgn** [comment] 2024-02-27 21:08
Again it happened today. I'm personally on Android, I have a colleague who is on iOS but won't be able to help with TestFlight

**Comment by Vaxter** [comment] 2024-02-27 21:18
> I have a possible fix on https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5596
> 
> But I need help testing from all of you, @paulchen @loopway @Vaxter @matbgn @0ki .
> 
> 
> 
> Here's the link to TestFlight https://testflight.apple.com/join/3gcYeoMr
> 
> Build version should be 4.47.0.58428.
> 
> 
> 
> Thanks!
> 
> Let me know if you have any questions.

Installed on all of my devices.
I'll give it a run for a couple of days and let you know.

**Comment by 0ki** [comment] 2024-02-27 23:59
I'd love to test, but the problem has fully disappeared on its own, so I'm afraid I might not be able to verify the fix atm.

**Comment by Vaxter** [comment] 2024-02-28 11:53
@paulchen Still happening. Now when phone is unlocked I sometimes can see the sender and content, and when locked still the same.
Notifications are set up to show everything even when locked.
Same on my iPad.

**Comment by diegolmello** [comment] 2024-02-28 13:30
@Vaxter Thanks for the feedback.
It looks exactly what I described on `known bugs` there, but but 
not only after boot https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5596

I'll have to investigate deeper.
I'm going to let you all know once I have more info.

**Comment by diegolmello** [comment] 2024-02-28 13:40
@Vaxter Try this workaround, but might be tricky to do:
- Install app from App Store
- Restart device
- Receive a push only after device is unlocked
- App is going to reuse that same valid instance to fetch content

If you do it, let me know if it works forever (or until you restart).
That might be what happened to @0ki

**Comment by harryb303** [comment] 2024-02-28 13:50
@diegolmello also been experiencing this issue since updating to 6.5 around the middle of January. Happens whether my iPhone is locked or unlocked. Updated to 6.6.1 today but problem persists. Installed the TestFlight build.

**Comment by harryb303** [comment] 2024-02-28 14:02
> @Vaxter Try this workaround, but might be tricky to do:
> 
>     * Install app from App Store
> 
>     * Restart device
> 
>     * Receive a push only after device is unlocked
> 
>     * App is going to reuse that same valid instance to fetch content
> 
> 
> If you do it, let me know if it works forever (or until you restart). That might be what happened to @0ki

Just tried this, reinstalled the App Store build over the TestFlight build, restarted the phone, unlocked, waited for a push notification and it showed the message content, then locked the phone and received another notification with the message content. Will report back if the issue comes back.

**Comment by diegolmello** [comment] 2024-02-28 14:04
Btw there's nothing that proves 6.5 is related to this issue.
Our backend team took a look at this last week and couldn't find anything.

On iOS, it's related to how MMKV is handled by iOS when phone is locked (and other behaviors).
On Android, I still need to investigate.

If this issue is something that's impacting your use case negatively, you should turn off the setting until we have a fix (or try the workaround above).

**Comment by ulope** [comment] 2024-02-28 14:31
I've just updated (due to being forced, I've learned to never trust RC updates because something breaks *every single damn time*) from 6.4.2 to 6.6.1 and now notifications all of a sudden are missing content so I'd say it'd pretty clearly related to the server version.

**Comment by diegolmello** [comment] 2024-02-28 14:34
@ulope Did you have the setting enabled before the update or was it enabled for you afterwards?

**Comment by ulope** [comment] 2024-02-28 15:11
I can't really say. I definitely didn't change anything except updating.

**Comment by paulchen** [comment] 2024-02-28 16:25
> @paulchen I wasn't able to reproduce the issue on Android at all. Let me know if it happens again.

@diegolmello The issue did not occur recently, neither for me nor for any of my users.

**Comment by diegolmello** [comment] 2024-02-28 18:12
6.5 moved some workspaces to the [Starter plan](https://www.rocket.chat/pricing), which means those workspaces now have access to almost all enterprise features.
Since `Secure Push Notifications` is enabled by default and it used to be a paid feature, now you're actually using it on Starter.

Let me know if it makes sense.

**Comment by matbgn** [comment] 2024-02-28 18:21
Really annoying in fact...

**Comment by harryb303** [comment] 2024-02-29 10:04
Issue has returned this morning. Have not restarted the phone or touched the app or our server.

**Comment by ulope** [comment] 2024-02-29 16:06
Still seeing this here as well. Users are starting to notice and complain :/

**Comment by diegolmello** [comment] 2024-02-29 16:35
https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/5496#issuecomment-1969053810

> If this issue is something that's impacting your use case negatively, you should turn off the setting until we have a fix

> Workspace -> Settings -> Push -> Privacy

<img width="599" alt="image" src="https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/804994/d8b0389b-d58b-4c42-a91c-59cc54d3e987">

**Comment by ulope** [comment] 2024-02-29 18:45
In our instance it's not possible to disable this setting. 

The toggle is disabled:
![](https://ds.ulo.pe//Screen-Shot-2024-02-29-19-43-50-afENwLrzo33O045t0mUpoic8QJGUA2eZHp90wsSdb2Dr4rVMWNIWiEdYdLWzc78Uq6IyXAG8VSmjufqU3bljG06yikh95zs1pl2C.png)

**Comment by diegolmello** [comment] 2024-02-29 20:49
@ulope What plan are you on right now?

**Comment by ulope** [comment] 2024-03-02 21:17
@diegolmello no plan, community edition.

**Comment by matheusbsilva137** [comment] 2024-03-04 17:19
@ulope have you been on Starter plan at some point and disabled it? Or have you always been on community?

**Comment by matbgn** [comment] 2024-03-04 17:22
Is there a way to fully switchback to community?

**Comment by ulope** [comment] 2024-03-05 13:45
@matheusbsilva137 Yes the upgrade to 6.6.1 auto-enrolled us to the starter plan (which I did not at all appreciate btw, overbearing marketing dark patterns like this just suck, and probably are illegal in a good number of countries I might add).

@matbgn Yes, totally intuitively you have to click the "cancel subscription" at the bottom edge of the manage subscription screen.

**Comment by 0ki** [comment] 2024-03-06 20:59
Notifications have randomly started working properly again this evening. No changes to client or server on our part.
About 1600-1700 UTC, I'd say.

Any ideas?

**Comment by 0ki** [comment] 2024-03-06 21:04
What did change, is that I rebooted my phone. Hmmm.

**Comment by 0ki** [comment] 2024-03-27 00:06
This started working randomly at one point and broke later that same day after I updated the Rocket Chat client on iOS. Hasn't been working since.

**Comment by svenseeberg** [comment] 2024-04-10 09:35
> This started working randomly at one point and broke later that same day after I updated the Rocket Chat client on iOS. Hasn't been working since.

Thats the same for us. It seems that it works for some time after restarting the service but then breaks.

**Comment by diegolmello** [comment] 2024-04-10 13:25
I'm going to send a new TestFlight version in a few days. Just need to finish testing something else first. I'll be in touch.

**Comment by mdoesburg** [comment] 2024-05-01 01:32
@diegolmello Any update on this? Not being to able to see previews anymore (on iOS) is getting really frustrating. 😂

**Comment by 0ki** [comment] 2024-05-13 11:26
An update from my side - still affected on iOs for the past month. Any plans on fixing?

**Comment by 0ki** [comment] 2024-06-25 16:01
Problem still here. Any more info that you need?

**Comment by 0ki** [comment] 2024-08-06 07:08
Since this has been stuck for half a year we found a stable workaround that I can recommend.
We installed [mattermost](https://github.com/mattermost) on a separate server, transferred the accounts and set up a [bridge](https://github.com/42wim/matterbridge).

People register in to mattermost app on their devices and get the notifications. Works nicely. The only downside is that mattermost opens instead of RocketChat when tapping on the notification.
We'll see how that goes, maybe moving everything to MM and leaving RC as a legacy channel via bridge is an option.

**Comment by diegolmello** [comment] 2024-08-13 13:26
Can you test Rocket.Chat iOS beta please? Version 4.51.0.64057.
https://testflight.apple.com/join/3gcYeoMr

For those on Android, can you check logs (or try to reproduce while checking logs) to understand if rate limiter is blocking requests to `push.get`.
It would help a lot.
Thanks!

**Closed** 2024-09-16 17:53 UTC
Labels: 🕵️ needs investigation
