### ISSUE TITLE
Last word of specific message not shown on android

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat.ReactNative#5826] opened 2024-08-12 15:34 UTC
### Description:

With version 4.50 it happend now and then the last word of a message went missing. Now I found a message I can reproduce the error with. The message is shown in the browser just fine. Just enter:

```
Hola Waldfee Gibst Du mal bitte OS und Browser durch, die Du für Jitsi benutzt? Hast Du bei Dir zu Hause irgendeine besondere Firewall? Wer ist der Internetanbieter und was die benutzte Übertragungstechnologie?
```

The word "Übertragungstechnologie" is not shown in android. Is the line break the problem maybe?
### Environment Information:

- Rocket.Chat Server Version: 6.11.0
- Rocket.Chat App Version: 4.50.1
- Device Name: pixel 6
- OS Version: android 14

### Steps to reproduce:

1. enter specifictext
2. last word gets missing

### Expected behavior:

entire text is shown.

### Actual behavior:

Some words are missing.

**Comment by charanbhatia** [comment] 2024-08-12 20:08
@himpierre @geekgonecrazy can you assign this issue to me?

**Comment by diegolmello** [comment] 2024-08-12 20:16
@charanbhatia if you want to do it, just do it

**Comment by Rohit3523** [comment] 2024-11-07 22:42
Cannot reproduce this issue
![Screenshot_2024_1108_041210.jpg](https://github.com/user-attachments/assets/cf33bc5e-1aef-4fbc-98c3-4d4cc9a089dd)

**Comment by diegolmello** [comment] 2024-11-08 14:21
Fixed on https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5892

**Closed by diegolmello** 2024-11-08 14:21 UTC
