### ISSUE TITLE
Clicking over the android notification will open rocket chat but lock on the splash

### ISSUE THREAD

**Issue by jsalatiel** [RocketChat/Rocket.Chat.ReactNative#1626] opened 2020-01-27 16:07 UTC
- Your Rocket.Chat Experimental app version: 4.2.4
- Your Rocket.Chat server version: docker latest image
- Device (or Simulator) you're running with: OnePlus

When I receive a message from rocket chat, the notification appear on my phone, but after clicking it rocket chant will hang forever on the splash screen. I need to close it, and open by clicking over its icon to see the message.

**Comment by djorkaeffalexandre** [comment] 2020-01-28 12:02
Hi @jsalatiel, does this happen with all notifications?
Did you try with `https: // open.rocket.chat` notifications?
Do you have any `push` settings changed on your server?

**Comment by leva3000** [comment] 2020-02-05 10:08
Hi @djorkaeffalexandre. We are experiencing the same issue on both Android and iOS apps. Can you suggest how to debug this issue? I didn't find any way to get information from incoming push (just assumed that generated push can consist wrong URL or something like that). Let me know if you need more details. Thanks!

**Comment by leva3000** [comment] 2020-02-05 11:48
The issue was in Site URL. It was set with HTTPS but from outside network our server is accessible only over HTTP. So it looks like push notifications were lead to the URL with HTTPS which can't be opened.

**Comment by octotep** [comment] 2020-07-13 03:09
I'm experiencing this exact problem with our custom compiled Rocket.Chat app with our own push notification certs. Our server is available over HTTPS, so the suggestion above doesn't resolve the problem for us. We've only tested on iOS so far so I cannot comment on Android.

To reproduce:

1. Make sure the Rocket.Chat app gets unloaded (either open a lot of apps, just wait for it to get unloaded in the background due to regular use, or simply force close it)
2. Receive a push notification and tap it.
3. The app will hang at the splash screen when opening when launched from a push notification

It's worth noting that if the app is not unloaded, push notifications work exactly as you expect they would. They only cause Rocket.Chat to hang at the splash screen if the app isn't already running. We don't have experience debugging a problem like this so we would appreciate some pointers on where to start looking

**Comment by diegolmello** [comment] 2020-07-13 12:20
@octotep Make sure `Site_Url` setting matches your server URL.

**Comment by DMuckerman** [comment] 2020-07-13 13:40
Hey Diego,

I can confirm our Site Url is pointing to the URL we use to access the web app, and I made sure I went back in and updated ROOT_URL for the docker container to also be correct, but I'm still seeing the mobile app hang when attempting to open a push notification after the app has been evicted from memory or force quit.

We're running the latest docker version and the latest build from the single-server branch for mobile.

**Closed** 2020-07-30 19:41 UTC
Labels: ℹ️ needs info, 🐛 bug
