### ISSUE TITLE
RocketChat's ReactNative app displays embedded images as blank screens

### ISSUE THREAD

**Issue by jliebers** [RocketChat/Rocket.Chat.ReactNative#3938] opened 2022-03-21 10:47 UTC
### Description:

In our team's rocketchat, we have a chatbot that embeds images in messages upon being triggered by a certain keyword.
To be more precise, it fetches the plan of our mensa, renders it through a php script to a jpg file and displays this embedded jpg file (given as `image_url` of a json that the bot fetches).
The embedded images are displayed fine in the webbrowser and the electron app, yet on mobile they show as blank/black screens.
We have confirmed this in our group on multiple devices (various Androids, also iOS).

Our chatbot (implemented as an outgoing integration in rocketchat server [0]) requests such json data: (I have shortened the output and truncated the URLs.)

```
{
   "text":"Here is this week's very tasty [...]",
   "attachments":[
      {
         "title":"[... NameOfOurMensa ...]",
         "title_link":"https://www.youtube.com/watch?v=qYS0EeaAUMw",
         "color":"#764FA5",
         "image_url":"https://example.org/mensaplan.jpg"
      }
   ]
}
```

It shows up like this on the webbrowser and the electron app:

![grafik](https://user-images.githubusercontent.com/24356915/159243640-da00ca2e-3362-459f-87cc-ae3e9fd703f1.png)

One can click it and view the jpeg in full size, which is then fine and readable.

On the ReactNative app the thumbnails shows fine as well:

![grafik](https://user-images.githubusercontent.com/24356915/159246151-f5f2bb99-929a-4323-91e9-87767ffc1658.png)

However, when opening the image by pressing on it to read it in full size, it does not show anything:

![grafik](https://user-images.githubusercontent.com/24356915/159245735-d01eaa7b-08e6-4b28-829a-72cc46f55b86.png)

### Environment Information:

- Rocket.Chat Server Version: 3.18.3
- Rocket.Chat App Version: 4.25.0.29370
- Device Name: Fairphone 4, 5G
- OS Version: Android 11

### Steps to reproduce:

1. Trigger the chatbot by posting its keyword, making it fetch the above-listed JSON object.
2. Press on the embedded image (as given by json-tag `image_url`)

### Expected behavior:

I expect to see the embedded image thumbnail now in full size so that I can read it well.

### Actual behavior:

I see a black screen (see last screenshot above).

### Additional context:

This might be related to #2836 or #2853 and #2836, yet for us the thumbnails work fine but maximizing the thumbnail does not work at all.

Thank you kindly in advance.

[0] https://docs.rocket.chat/guides/administration/admin-panel/integrations

**Comment by reinaldonetof** [comment] 2023-03-09 21:15
@jliebers Hello, Jonathan! I hope you are well!

So, the problem is how the attachments handle the links, at mobile devices we are prioritizing rendering the `title_link` above the `image_url`. As you are sending a youtube link, the attachment is trying to render it instead of the image.

If you are still struggling with that, you can use the same link as the image_url in the title_link, or just remove the title_link.

I will close this issue, but let me know if you need something more.

**Closed by reinaldonetof** 2023-03-09 21:15 UTC
