### ISSUE TITLE
In some cases, new messages in conversations are not loaded

### ISSUE THREAD

**Issue by davidlougheed** [RocketChat/Rocket.Chat.ReactNative#1305] opened 2019-10-14 22:16 UTC
- Your Rocket.Chat Experimental app version: 1.21.1 12049
- Your Rocket.Chat server version: 2.1.0
- Device (or Simulator) you're running with: iPhone 8

Basically, in some cases messages are available in the preview but don't appear when the channel is clicked on. App restarts don't fix this, and new messages may appear as normal, leading to a fragmented conversation history.

Had a conversation with @diegolmello about this.

**Comment by kuluev** [comment] 2019-11-04 09:45
Same on Android
App version: 4.0.2
Server: 2.2.0

**Comment by diegolmello** [comment] 2019-11-04 11:47
@davidlougheed @kuluev Can you test on Experimental 1.20.2.12436? Thanks.

**Comment by mrsimpson** [comment] 2019-11-04 15:29
@diegolmello Not very sure whether this is the same root cause, but at least similar:
One of our users reported to find the app (Android, 4.0.2, Server 1.3.2) in a state where the app appeared to be loaded (he could browse channels) but did not receive any notifications or message updates.

**Comment by diegolmello** [comment] 2019-11-04 15:47
@mrsimpson Are you able to reproduce it?
I'm going to release a 4.0.3 beta in a few hours.
Please ask them to join beta and try again.
Let me know if the issue persists and we'll fix it.
Thanks.

**Comment by J0kerFace** [comment] 2019-11-04 21:25
The current experimental version didnt fix this problem for us.

**Comment by ankar84** [comment] 2019-11-05 04:28
I definitely experienced this problem on one of the previous experimental versions of RN.

**Comment by davidlougheed** [comment] 2019-11-07 17:04
Ok this seems to be fixed for me after a few days of testing @diegolmello 
I've ran into a few other messaging bugs but this one at least I haven't seen since.

**Comment by diegolmello** [comment] 2019-11-07 17:47
Let's try #1373.
I'll test for the rest of the day.
If it's better, I'll release as beta asap.

**Comment by davidlougheed** [comment] 2019-11-08 20:42
@diegolmello latest seems to have caused some issues loading messages in the channel list screen; I'm not getting the latest updates unless I click on each channel individually. I'll try reinstalling and report back

**Comment by diegolmello** [comment] 2019-11-08 20:45
Ok. Remember to always say the correct version.
Latest version to you is almost never the same to me :)

**Comment by davidlougheed** [comment] 2019-11-08 21:06
oops, my bad. version is 1.20.3 (12541)

**Comment by davidlougheed** [comment] 2019-11-08 22:09
Actually on that build if I log out and back in nothing loads at all 
![4A5D93BD-A9EF-41D2-A1EC-DA1703B4033B](https://user-images.githubusercontent.com/357970/68513998-81fe8d00-024a-11ea-9702-5506820b5742.png)

**Comment by johnlund** [comment] 2019-12-02 02:41
Seeing this also on:

Android version: 4.0.6.2092
Server: 2.1.1

**Comment by parkerrome** [comment] 2019-12-03 02:58
Having members report similar issues on iPhones. Is there a beta that fixes this?

We're running the latest release (1.20) and server version 2.1.1.

**Comment by diegolmello** [comment] 2019-12-03 11:18
Latest release is 1.24.0. There's even a TestFlight with 1.25.0 already.
Try again on those versions.

**Comment by diegolmello** [comment] 2019-12-03 16:58
Fixed by #1410

**Closed by diegolmello** 2019-12-03 16:58 UTC
Labels: 🐛 bug
