### ISSUE TITLE
"Jump to Message" Feature

### ISSUE THREAD

**Issue by semartsal** [RocketChat/Rocket.Chat.ReactNative#2998] opened 2021-03-19 04:12 UTC
### Description:

 Hey, Guys. Can u tell, when will the function "Jump to message" be available in the mobile application ? or when development is planned

### Environment Information:

- Rocket.Chat Server Version: 3.11.1
- Rocket.Chat App Version: 4.15
- Device Name: any
- OS Version: Android, iOS

### Steps to reproduce:

1. 
2. 
3.

**Comment by ankar84** [comment] 2021-03-19 06:20
Duplicate of https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1315

**Closed** 2021-03-19 11:51 UTC
