### ISSUE TITLE
Apply Certificate doesn't work on Android

### ISSUE THREAD

**Issue by josephsmendoza** [RocketChat/Rocket.Chat.ReactNative#3172] opened 2021-05-28 22:56 UTC
`I did try that "apply certificate" option but on my device it does nothing. Regardless that button isn't necessary on android, which is the issue at hand.`

I confirm this, the button "use your certificate" does not work, when you click on it, the screen darkens for a second and nothing happens, version Android 10, phone Xiaomi Redmi Note T8, letest version rocketchat from google play.

_Originally posted by @so121183gak in https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/3100#issuecomment-850627793_

**Comment by so121183gak** [comment] 2021-05-29 12:23
I solved the issue of logging in on an android device without using the "use your certificate" button, it turns out that in the crt certificate, you need to add the entire certificate chain to nginx. I acted on these instructions
https://www.leaderssl.ru/articles/131-ustanovka-sertifikata-nginx

**Comment by josephsmendoza** [comment] 2021-05-30 03:08
That only works if you have paid for a certificate and is a different issue to this one.

**Comment by so121183gak** [comment] 2021-05-30 20:30
> That only works if you have paid for a certificate or have a public facing domain and is a different issue to this one.

for me it works with Let's Encrypt certificate.

**Comment by josephsmendoza** [comment] 2021-05-30 20:41
Which means you have a public facing domain. My server is behind a vpn only.

**Comment by so121183gak** [comment] 2021-05-31 07:20
this is correct, but it doesn't matter where you use this approach, you can create your own Let's Encryp certificate and also push it to nginx.

**Comment by josephsmendoza** [comment] 2021-05-31 07:29
You cannot create a Let's Encrypt certificate, they create the cert and send it to you after verifying that you own the domain name, and it will only work for that domain.

**Comment by so121183gak** [comment] 2021-05-31 08:09
I think there is a variation, try differently https://www.youtube.com/watch?v=DKm8t5aMVS8&list=FLZAsqd1W-43qvaBgl4nJA-w&index=3

**Comment by josephsmendoza** [comment] 2021-05-31 09:45
He says about 3 minutes in that let's encrypt requires a static IP connected to a domain name for their system to work. That's not possible without a public facing ip.

**Comment by josephsmendoza** [comment] 2021-05-31 09:48
Please stop leaving unrelated comments on issue pages, you are distracting from the issue at hand.

**Comment by johncrisp** [comment] 2021-06-03 23:02
As per this comment:

> Originally posted by @so121183gak in #3100 (comment)

Closing as a duplicate of https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/3100

**Closed by johncrisp** 2021-06-03 23:02 UTC

**Comment by josephsmendoza** [comment] 2021-06-04 01:05
This is not a duplicate. The explanation left on the original issue belongs here. That explanation doesn't solve the issue either, but rather changes it's description, which is that the button appears to do nothing. A toast or message box should be added to show what has happened.
