### ISSUE TITLE
Reaching server via VPN

### ISSUE THREAD

**Issue by AlexKalopsia** [RocketChat/Rocket.Chat.ReactNative#3156] opened 2021-05-25 10:18 UTC
Hi, I currently run RocketChat on a docker container.
The docker container was exposed via reverse proxy (rocketchat.mydomain.com) and the Android app would correctly reach the server. 

I am now trying to only reach RC via VPN, so getting rid of all references to the external url, for sacureity reasons. The docker now uses http://localip:port as URL, which I reach via VPN.

The issue now is that the app doesn't allow me to enter http://localip:port with the message

```
CLEARTEXT communication to ip not permitted by network security policy.
```

My question is, is there absolutely no way to use the app and rely on a VPN? Am I forced to expose my RocketChat instance to an external url?

**Comment by diegolmello** [comment] 2021-05-25 11:01
The issue is that you're using http instead of https

**Comment by diegolmello** [comment] 2021-05-25 12:08
You have a reason: Apple enforces you to use https and Google's best practices tell you the same.
So we disallow http on our app.

**Comment by AlexKalopsia** [comment] 2021-05-25 13:27
So what you are saying that I cannot use the app to connect to my server with a VPN connection?

**Comment by johncrisp** [comment] 2021-05-25 17:36
> So what you are saying that I cannot use the app to connect to my server with a VPN connection?

Not via http, no.

As Diego said, Apple enforces https, and Google strongly recommends it, and will eventually disable it as well.

You can still use a https connection over your VPN.

Set up a proper self signed certificate and reverse proxy on the server, and VPN in.

Closing as this does not appear to be a bug  - for further support please ask in https://open.rocket.chat #support or https://forums.rocket.chhat

Thanks.

**Closed by johncrisp** 2021-05-25 17:36 UTC
