### ISSUE TITLE
SSO 2FA with FIDO not working

### ISSUE THREAD

**Issue by aasseman** [RocketChat/Rocket.Chat.ReactNative#2284] opened 2020-07-13 18:53 UTC
Rocket.Chat Experimental app version: 4.8.0.17969
Rocket.Chat server version: 3.3
Device: Google Pixel 2, Android 10

I am currently using GSuite SAML. It works perfectly in the browser.
In the Android app, when logging in, there is no way to use a FIDO key, as the SAML login page is using the app's browser, and cannot talk to the key.

A possible solution would be to open the SAML login page in the external browser, as Slack does.

**Comment by diegolmello** [comment] 2020-07-20 12:10
I'm unable to reproduce here.
Send me a test user at https://open.rocket.chat. I'm `@diego.mello`.

**Comment by aasseman** [comment] 2020-07-27 18:23
Found easier steps to reproduce the issue.
The problem seems to impact SSO in general. So it can be triggered by trying to login with Google OAuth, with a google account using FIDO 2FA.

**Comment by b90g** [comment] 2020-12-09 09:16
iOS 14.2
App: 4.12.1.317
Server: 3.9.1

Setup on my Account is the _Timebased_ Passwords  with SAML.
Sends me back to SAML Startpage after shortly flashing me the 2fa dialog.
Can provide video on request.

Want a new issue?( sounds like the same to me.)

**Comment by diegolmello** [comment] 2020-12-09 11:39
@b90g yeah, please create a new issue.
The focus of this one is FIDO actually.
Thanks.

**Comment by b90g** [comment] 2020-12-09 13:02
> @b90g yeah, please create a new issue.
> The focus of this one is FIDO actually.
> Thanks.

#2703 good luck with FIDO here.

**Comment by diegolmello** [comment] 2021-06-29 13:51
#3134 Google OAuth is now made on external browsers, so that might fix FIDO.
It's still missing for other OAuth or SSO though.
Let me know if this is enough to close this issue.
Thank you.

**Closed** 2021-07-13 16:52 UTC
Labels: ℹ️ needs info

**Comment by KramNamez** [comment] 2023-10-04 07:49
I realize this is an old issue, but we are using our own SSO (via Keycloak), and use FIDO keys for that. Right now, that means that the mobile app doesn't allow login (unless we fall back to TOTP, but we'd like to get rid of those in the future).

Could you please apply the fix to _all_ OAUTH/SSO Logins, not just Google?
