### ISSUE TITLE
No GCM token registered when i use the Rocket chat experimental app

### ISSUE THREAD

**Issue by nixxou** [RocketChat/Rocket.Chat.ReactNative#2455] opened 2020-09-10 07:36 UTC
### Description:

If i log-in using the experimental rocket chat app on the google play store, and try to do a test push, it show : "They are no tokens for this user".
If i disconect and reconect using the Rocket chat classic app on the play store, i have a push token registered for my account (even if push are not working from rocket chat on my phone, but i guess it's a separate issue : https://github.com/RocketChat/Rocket.Chat/issues/18541 )

### Environment Information:

- Rocket.Chat Server Version: 3.5.2
- Rocket.Chat App Version: 4.11.0.20023
- Device Name: Black Shark 2
- OS Version:  Android 9

### Steps to reproduce:

1. Login in Rocket Chat Experimental
2. Done, there is no gcm token registered

### Expected behavior:

A GCM token should be registered upon login

**Comment by nixxou** [comment] 2020-09-10 08:01
After some investigations, it seems like the GCM token was registered on an other account where i was logged previously.
A normal behavior would be to reassign the token to the account you just signed in, but that's not what happen here.

Anyway, that sadly does not fix my issue with https://github.com/RocketChat/Rocket.Chat/issues/18541

**Comment by diegolmello** [comment] 2020-09-28 14:40
It looks like the issue is on the server. Closing.

**Closed by diegolmello** 2020-09-28 14:40 UTC
