### ISSUE TITLE
Caching and persistence of rooms that the user does not have access to anymore.

### ISSUE THREAD

**Issue by MHFDoge** [RocketChat/Rocket.Chat.ReactNative#3841] opened 2022-03-04 21:48 UTC
### Description:

I've noticed for a while there seems to be a problem with how the mobile app caches rooms and other data.

### Environment Information:

- Rocket.Chat Server Version: 4.5.0 
- Rocket.Chat App Version: 4.25.0.20370
- Device Name: Samsung Galaxy S21 Ultra
- OS Version: Android 12

### Steps to reproduce:

1. Have an administrator account active on one device,(a browser works), create a private room, and add the non-administrator account to that room.
2. Using said non-administrator account on the mobile app, open the app, and open the new channel, allowing the messages to load if there are any.
3. Close the Rocket.Chat mobile app
4. Using the administrator account, remove the non-administrator account from the room.
5. Back on the phone, re-open the mobile app.
### Expected behavior:

The channel, which you no longer have access to, should not be listed nor should any messages or message history be retrievable.

### Actual behavior:

The channel, which you no longer have access to, is still listed as it is cached in-app, and is only able to be removed by manually refreshing the local cache.
![image](https://user-images.githubusercontent.com/46448580/156844961-8074ce08-3d67-4caf-8f43-05a75522f056.png)
![image](https://user-images.githubusercontent.com/46448580/156844979-e3840805-08cb-4438-a735-276f03dffc39.png)

### Additional context:

In our use case, public rooms are created at scheduled times and remain open for around 90 minutes, during which, users tend to pop in and out. When the room is closed, to protect user privacy and enforce a confidentiality policy, each user is removed from the room, the room is marked as read only and private, and then finally archived. This issue prevents us from fully removing the room from visibility to the user, and thus, from maintaining the aforementioned confidentiality policy.

**Comment by ankar84** [comment] 2022-03-05 05:09
Looks like duplicate of https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/3756

**Comment by MHFDoge** [comment] 2022-03-05 17:31
Oh, true it does appear to be a duplicate. Sorry about that.

**Closed** 2023-01-20 17:19 UTC
